[INFO] Starting execution.
[INFO] Downloading package list from PyPI ...
[INFO] (0) This package is up to date.
[ERROR] (0-0) This package does not have downloadable releases.
[INFO] (0-0-1) This package is up to date.
[INFO] (0-core-client) This package is up to date.
[INFO] (0-orchestrator) This package is up to date.
[INFO] (00print-lol) This package is up to date.
[ERROR] (00smalinux) This package does not have downloadable releases.
[ERROR] (01changer) This package does not have downloadable releases.
[INFO] (021) This package is up to date.
[INFO] (02exercicio) This package is up to date.
[INFO] (0805nexter) This package is up to date.
[INFO] (090807040506030201testpip) Data has been updated for this package.
[INFO] (0fela) This package is up to date.
[INFO] (0wdg9nbmpm) This package is up to date.
[INFO] (0wned) This package is up to date.
[INFO] (0x) This package is up to date.
[INFO] (0x-order-utils) This package is up to date.
[INFO] (0x10c-asm) This package is up to date.
[ERROR] (1) This package does not have downloadable releases.
[INFO] (100bot) This package is up to date.
[INFO] (1020-nester) This package is up to date.
[INFO] (10daysweb) This package is up to date.
[INFO] (115wangpan) This package is up to date.
[INFO] (11l) This package is up to date.
[INFO] (12factor-vault) This package is up to date.
[INFO] (131228-pytest-1) This package is up to date.
[INFO] (1337) This package is up to date.
[INFO] (153957-theme) This package is up to date.
[INFO] (15five-django-ajax-selects) This package is up to date.
[INFO] (17monip) This package is up to date.
[ERROR] (18-e) This package does not have downloadable releases.
[INFO] (199fix) This package is up to date.
[INFO] (1and1) This package is up to date.
[INFO] (1c-utilites) This package is up to date.
[INFO] (1dyfolabs-test-script) This package is up to date.
[INFO] (1ee) This package is up to date.
[INFO] (1nester) This package is up to date.
[INFO] (1pass) This package is up to date.
[INFO] (1to001) This package is up to date.
[ERROR] (2) Could not get a response from API for this package. See below for details.
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/pypicontents/api/pypi.py", line 264, in get_pkgdata
    timeout=10).read()
  File "/usr/lib/python3.5/urllib/request.py", line 163, in urlopen
    return opener.open(url, data, timeout)
  File "/usr/lib/python3.5/urllib/request.py", line 472, in open
    response = meth(req, response)
  File "/usr/lib/python3.5/urllib/request.py", line 582, in http_response
    'http', request, response, code, msg, hdrs)
  File "/usr/lib/python3.5/urllib/request.py", line 510, in error
    return self._call_chain(*args)
  File "/usr/lib/python3.5/urllib/request.py", line 444, in _call_chain
    result = func(*args)
  File "/usr/lib/python3.5/urllib/request.py", line 590, in http_error_default
    raise HTTPError(req.full_url, code, msg, hdrs, fp)
urllib.error.HTTPError: HTTP Error 404: Not Found

[INFO] (2008webcrawler) This package is up to date.
[ERROR] (2013007-pyh) This package does not have downloadable releases.
[INFO] (2048) This package is up to date.
[INFO] (2112) This package is up to date.
[INFO] (23andme-to-vcf) This package is up to date.
[INFO] (24to25) This package is up to date.
[INFO] (2969nester) This package is up to date.
[ERROR] (2c-py) Could not extract data from this package. See below for details.
This package download URL does not point to a valid file: "http://code.google.com/p/2c-python/downloads/"
[ERROR] (2dfly-manbanzhen) Could not get a response from API for this package. See below for details.
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/pypicontents/api/pypi.py", line 264, in get_pkgdata
    timeout=10).read()
  File "/usr/lib/python3.5/urllib/request.py", line 163, in urlopen
    return opener.open(url, data, timeout)
  File "/usr/lib/python3.5/urllib/request.py", line 472, in open
    response = meth(req, response)
  File "/usr/lib/python3.5/urllib/request.py", line 582, in http_response
    'http', request, response, code, msg, hdrs)
  File "/usr/lib/python3.5/urllib/request.py", line 510, in error
    return self._call_chain(*args)
  File "/usr/lib/python3.5/urllib/request.py", line 444, in _call_chain
    result = func(*args)
  File "/usr/lib/python3.5/urllib/request.py", line 590, in http_error_default
    raise HTTPError(req.full_url, code, msg, hdrs, fp)
urllib.error.HTTPError: HTTP Error 404: Not Found

[INFO] (2fa) This package is up to date.
[INFO] (2factorcli) This package is up to date.
[INFO] (2gis) This package is up to date.
[ERROR] (2jjtt6cwa6) This package does not have downloadable releases.
[INFO] (2lazy2rest) This package is up to date.
[INFO] (2mp3) This package is up to date.
[INFO] (2mp4) This package is up to date.
[INFO] (2or3) This package is up to date.
[INFO] (2to3) This package is up to date.
[INFO] (3) This package is up to date.
[INFO] (3-1) This package is up to date.
[INFO] (3049bab9) This package is up to date.
[INFO] (311devs-peewee) This package is up to date.
[INFO] (36-chambers) This package is up to date.
[INFO] (36ban-commons) This package is up to date.
[ERROR] (3color-press) This package does not have downloadable releases.
[ERROR] (3d-bin-container-packing) Could not get a response from API for this package. See below for details.
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/pypicontents/api/pypi.py", line 264, in get_pkgdata
    timeout=10).read()
  File "/usr/lib/python3.5/urllib/request.py", line 163, in urlopen
    return opener.open(url, data, timeout)
  File "/usr/lib/python3.5/urllib/request.py", line 472, in open
    response = meth(req, response)
  File "/usr/lib/python3.5/urllib/request.py", line 582, in http_response
    'http', request, response, code, msg, hdrs)
  File "/usr/lib/python3.5/urllib/request.py", line 504, in error
    result = self._call_chain(*args)
  File "/usr/lib/python3.5/urllib/request.py", line 444, in _call_chain
    result = func(*args)
  File "/usr/lib/python3.5/urllib/request.py", line 696, in http_error_302
    return self.parent.open(new, timeout=req.timeout)
  File "/usr/lib/python3.5/urllib/request.py", line 472, in open
    response = meth(req, response)
  File "/usr/lib/python3.5/urllib/request.py", line 582, in http_response
    'http', request, response, code, msg, hdrs)
  File "/usr/lib/python3.5/urllib/request.py", line 510, in error
    return self._call_chain(*args)
  File "/usr/lib/python3.5/urllib/request.py", line 444, in _call_chain
    result = func(*args)
  File "/usr/lib/python3.5/urllib/request.py", line 590, in http_error_default
    raise HTTPError(req.full_url, code, msg, hdrs, fp)
urllib.error.HTTPError: HTTP Error 404: Not Found

[INFO] (3d-wallet-generator) This package is up to date.
[INFO] (3debt) This package is up to date.
[INFO] (3dfunctiongrapher) This package is up to date.
[INFO] (3edit) Data has been updated for this package.
[INFO] (3lwg) This package is up to date.
[ERROR] (3t) This package does not have downloadable releases.
[INFO] (3to2) This package is up to date.
[INFO] (3to2-py3k) This package is up to date.
[INFO] (3xsd) This package is up to date.
[INFO] (40wt-common-tasks) This package is up to date.
[ERROR] (42) This package does not have downloadable releases.
[INFO] (42cc-pystyle) This package is up to date.
[INFO] (42qucc) This package is up to date.
[INFO] (440-create-user) This package is up to date.
[INFO] (4cdl) This package is up to date.
[INFO] (4ch) This package is up to date.
[INFO] (4chan) This package is up to date.
[INFO] (4chandownloader) This package is up to date.
[INFO] (4scanner) This package is up to date.
[ERROR] (4suite) This package does not have downloadable releases.
[INFO] (4suite-xml) This package is up to date.
[INFO] (5) This package is up to date.
[INFO] (51degrees-mobile-detector) This package is up to date.
[INFO] (51degrees-mobile-detector-lite-pattern-wrapper) This package is up to date.
[INFO] (51degrees-mobile-detector-trie-wrapper) This package is up to date.
[INFO] (51degrees-mobile-detector-v3-trie-wrapper) This package is up to date.
[INFO] (51degrees-mobile-detector-v3-wrapper) This package is up to date.
[INFO] (51pub-pymodules) This package is up to date.
[INFO] (51pubmodules) This package is up to date.
[INFO] (5minute) This package is up to date.
[INFO] (5o4drel5mk) This package is up to date.
[INFO] (652ga) This package is up to date.
[INFO] (69) This package is up to date.
[INFO] (7) This package is up to date.
[ERROR] (73-portlet-links) This package does not have downloadable releases.
[INFO] (73-unlockitems) This package is up to date.
[INFO] (7i96) This package is up to date.
[INFO] (7lk-ocr-deploy) This package is up to date.
[ERROR] (7q-nester) This package does not have downloadable releases.
[INFO] (7th) This package is up to date.
[INFO] (7xydothis) This package is up to date.
[INFO] (908dist) This package is up to date.
[INFO] (91downloader) This package is up to date.
[INFO] 
[INFO] 
[INFO] Total packages: 109
[INFO]     Packages processed: 109
[INFO]         Packages updated: 2
[INFO]         Packages up-to-date: 90
[INFO]         Packages without response: 3
[INFO]         Packages without urls: 0
[INFO]         Packages without downloads: 13
[INFO]         Packages with data errors: 1
[INFO]     Packages not processed: 0
[INFO] 
[INFO] 
[INFO] Ending execution.
