[INFO] Starting execution.
[INFO] Downloading package list from PyPI ...
[ERROR] (p) This package does not have downloadable releases.
[INFO] (p-19movies) This package is up to date.
[INFO] (p-ages) This package is up to date.
[INFO] (p-astro) This package is up to date.
[INFO] (p-list) This package is up to date.
[INFO] (p-nester) This package is up to date.
[INFO] (p-stone-labs) This package is up to date.
[INFO] (p-tqdm) This package is up to date.
[INFO] (p-tree) This package is up to date.
[INFO] (p-url) This package is up to date.
[ERROR] (p-x) Could not extract data from this package. See below for details.
"http://www.mired.org/downloads/applet-0.2.tgz" file could not be downloaded. See below for details.
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/pypicontents/api/pypi.py", line 107, in download_tar
    f.write(urlopen(url=urlesc(pkgurl), timeout=10).read())
  File "/usr/lib/python3.5/urllib/request.py", line 163, in urlopen
    return opener.open(url, data, timeout)
  File "/usr/lib/python3.5/urllib/request.py", line 472, in open
    response = meth(req, response)
  File "/usr/lib/python3.5/urllib/request.py", line 582, in http_response
    'http', request, response, code, msg, hdrs)
  File "/usr/lib/python3.5/urllib/request.py", line 510, in error
    return self._call_chain(*args)
  File "/usr/lib/python3.5/urllib/request.py", line 444, in _call_chain
    result = func(*args)
  File "/usr/lib/python3.5/urllib/request.py", line 590, in http_error_default
    raise HTTPError(req.full_url, code, msg, hdrs, fp)
urllib.error.HTTPError: HTTP Error 404: Not Found

[INFO] (p01-accelerator) This package is up to date.
[INFO] (p01-build) This package is up to date.
[INFO] (p01-buildouthttp) This package is up to date.
[INFO] (p01-cdn) This package is up to date.
[INFO] (p01-cgi) This package is up to date.
[INFO] (p01-checker) This package is up to date.
[INFO] (p01-dashboard) This package is up to date.
[INFO] (p01-editor) This package is up to date.
[INFO] (p01-elasticsearch) This package is up to date.
[INFO] (p01-elasticstub) This package is up to date.
[INFO] (p01-env) This package is up to date.
[INFO] (p01-form) This package is up to date.
[INFO] (p01-fsfile) This package is up to date.
[INFO] (p01-fswidget) This package is up to date.
[INFO] (p01-geo) This package is up to date.
[INFO] (p01-json) This package is up to date.
[INFO] (p01-kibana) This package is up to date.
[INFO] (p01-locales) This package is up to date.
[INFO] (p01-memcache) This package is up to date.
[INFO] (p01-neo4jstub) This package is up to date.
[INFO] (p01-oid) This package is up to date.
[INFO] (p01-pagelet) This package is up to date.
[INFO] (p01-publisher) This package is up to date.
[INFO] (p01-recipe-cdn) This package is up to date.
[INFO] (p01-recipe-setup) This package is up to date.
[INFO] (p01-releaser) This package is up to date.
[INFO] (p01-remote) This package is up to date.
[INFO] (p01-sampledata) This package is up to date.
[INFO] (p01-sampler) This package is up to date.
[INFO] (p01-schema) This package is up to date.
[INFO] (p01-secureprincipal) This package is up to date.
[INFO] (p01-securitypolicy) This package is up to date.
[INFO] (p01-session) This package is up to date.
[INFO] (p01-statsd) This package is up to date.
[INFO] (p01-stemmer) This package is up to date.
[INFO] (p01-testbrowser) This package is up to date.
[INFO] (p01-tester) This package is up to date.
[INFO] (p01-tmp) This package is up to date.
[INFO] (p01-util) This package is up to date.
[INFO] (p01-vocabulary-cache) This package is up to date.
[INFO] (p01-vocabulary-country) This package is up to date.
[INFO] (p01-vocabulary-language) This package is up to date.
[INFO] (p01-vocabulary-legacy) This package is up to date.
[INFO] (p01-widget-password) This package is up to date.
[INFO] (p01-zmi) This package is up to date.
[INFO] (p029) This package is up to date.
[INFO] (p0f) This package is up to date.
[INFO] (p1) This package is up to date.
[INFO] (p1-bank) This package is up to date.
[INFO] (p1-indexer) This package is up to date.
[INFO] (p1-notif) This package is up to date.
[INFO] (p1-queue) This package is up to date.
[ERROR] (p10) This package does not have downloadable releases.
[INFO] (p1tr) This package is up to date.
[INFO] (p2) This package is up to date.
[INFO] (p2-overload) This package is up to date.
[INFO] (p22p) This package is up to date.
[INFO] (p24) This package is up to date.
[INFO] (p29) This package is up to date.
[INFO] (p2api) This package is up to date.
[INFO] (p2f) This package is up to date.
[INFO] (p2k) This package is up to date.
[INFO] (p2mfg) This package is up to date.
[INFO] (p2p) This package is up to date.
[INFO] (p2p-addons) This package is up to date.
[INFO] (p2p-grpc-blockchain) This package is up to date.
[INFO] (p2p-latimes) This package is up to date.
[INFO] (p2p-python) This package is up to date.
[INFO] (p2p-tribune) This package is up to date.
[INFO] (p2pem) This package is up to date.
[INFO] (p2pnet) This package is up to date.
[INFO] (p2pool-vtc) This package is up to date.
[INFO] (p2pproxiesauthorizer) This package is up to date.
[INFO] (p2pshare) This package is up to date.
[INFO] (p2psip) This package is up to date.
[INFO] (p2radio) This package is up to date.
[INFO] (p2tg) This package is up to date.
[INFO] (p2tool) This package is up to date.
[INFO] (p2v) This package is up to date.
[INFO] (p2whois) This package is up to date.
[INFO] (p3) This package is up to date.
[INFO] (p3-amazon-jp-tool) This package is up to date.
[INFO] (p3-bitbucket) This package is up to date.
[INFO] (p3-bittrex) This package is up to date.
[INFO] (p3270) This package is up to date.
[INFO] (p35-nester) This package is up to date.
[ERROR] (p3d) Could not extract data from this package. See below for details.
".git" extension not supported.
[INFO] (p3d3) This package is up to date.
[INFO] (p3mail) This package is up to date.
[INFO] (p4) This package is up to date.
[INFO] (p40-learning-distribution) This package is up to date.
[INFO] (p4a-audio) This package is up to date.
[INFO] (p4a-build) This package is up to date.
[INFO] (p4a-calendar) This package is up to date.
[INFO] (p4a-common) This package is up to date.
[INFO] (p4a-django) This package is up to date.
[INFO] (p4a-fileimage) This package is up to date.
[INFO] (p4a-image) This package is up to date.
[INFO] (p4a-ploneaudio) This package is up to date.
[INFO] (p4a-plonecalendar) This package is up to date.
[INFO] (p4a-ploneevent) This package is up to date.
[INFO] (p4a-ploneimage) This package is up to date.
[INFO] (p4a-plonetagging) This package is up to date.
[INFO] (p4a-plonevideo) This package is up to date.
[INFO] (p4a-plonevideoembed) This package is up to date.
[INFO] (p4a-subtyper) This package is up to date.
[INFO] (p4a-video) This package is up to date.
[INFO] (p4a-videoembed) This package is up to date.
[INFO] (p4a-z2utils) This package is up to date.
[INFO] (p4benchmark) This package is up to date.
[INFO] (p4clean) This package is up to date.
[ERROR] (p4client) Could not extract data from this package. See below for details.
"http://www.mired.org/downloads/P4Client-1.0.tar.gz" file could not be downloaded. See below for details.
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/pypicontents/api/pypi.py", line 107, in download_tar
    f.write(urlopen(url=urlesc(pkgurl), timeout=10).read())
  File "/usr/lib/python3.5/urllib/request.py", line 163, in urlopen
    return opener.open(url, data, timeout)
  File "/usr/lib/python3.5/urllib/request.py", line 472, in open
    response = meth(req, response)
  File "/usr/lib/python3.5/urllib/request.py", line 582, in http_response
    'http', request, response, code, msg, hdrs)
  File "/usr/lib/python3.5/urllib/request.py", line 510, in error
    return self._call_chain(*args)
  File "/usr/lib/python3.5/urllib/request.py", line 444, in _call_chain
    result = func(*args)
  File "/usr/lib/python3.5/urllib/request.py", line 590, in http_error_default
    raise HTTPError(req.full_url, code, msg, hdrs, fp)
urllib.error.HTTPError: HTTP Error 404: Not Found

[INFO] (p4d) This package is up to date.
[ERROR] (p4d-langlet) Could not extract data from this package. See below for details.
"https://files.pythonhosted.org/packages/9a/92/de461679d73caffccf8cf665e869823f6751fde5bcda80771e11db6b985a/P4D%20Langlet-1.2.4-py2.5.tar.gz" file could not be downloaded. See below for details.
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/pypicontents/api/pypi.py", line 107, in download_tar
    f.write(urlopen(url=urlesc(pkgurl), timeout=10).read())
  File "/usr/lib/python3.5/urllib/request.py", line 163, in urlopen
    return opener.open(url, data, timeout)
  File "/usr/lib/python3.5/urllib/request.py", line 472, in open
    response = meth(req, response)
  File "/usr/lib/python3.5/urllib/request.py", line 582, in http_response
    'http', request, response, code, msg, hdrs)
  File "/usr/lib/python3.5/urllib/request.py", line 510, in error
    return self._call_chain(*args)
  File "/usr/lib/python3.5/urllib/request.py", line 444, in _call_chain
    result = func(*args)
  File "/usr/lib/python3.5/urllib/request.py", line 590, in http_error_default
    raise HTTPError(req.full_url, code, msg, hdrs, fp)
urllib.error.HTTPError: HTTP Error 404: Not Found

[ERROR] (p4dti) Could not extract data from this package. See below for details.
This package download URL does not point to a valid file: "http://www.ravenbrook.com/project/p4dti/release/"
[INFO] (p4j) This package is up to date.
[INFO] (p4p) This package is up to date.
[INFO] (p4python) This package is up to date.
[INFO] (p4pythoninstaller) This package is up to date.
[INFO] (p4rr0t007) This package is up to date.
[INFO] (p4swamp) This package is up to date.
[INFO] (p4util) This package is up to date.
[INFO] (p5) This package is up to date.
[INFO] (p5-py) This package is up to date.
[INFO] (p55py) This package is up to date.
[INFO] (p5py) This package is up to date.
[INFO] (p7doi) This package is up to date.
[INFO] (p7edt2ics) This package is up to date.
[INFO] (p7magma) This package is up to date.
[INFO] (p8dl) This package is up to date.
[INFO] (p929) This package is up to date.
[INFO] (pa) This package is up to date.
[INFO] (pa-pylibs) This package is up to date.
[INFO] (pa-ringbuffer) This package is up to date.
[INFO] (pa11ycrawler) This package is up to date.
[INFO] (paab-policy) This package is up to date.
[INFO] (paano) This package is up to date.
[INFO] (paapi) This package is up to date.
[INFO] (paas-star) This package is up to date.
[INFO] (paascli) This package is up to date.
[ERROR] (paasmer-lib) Could not get a response from API for this package. See below for details.
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/pypicontents/api/pypi.py", line 264, in get_pkgdata
    timeout=10).read()
  File "/usr/lib/python3.5/urllib/request.py", line 163, in urlopen
    return opener.open(url, data, timeout)
  File "/usr/lib/python3.5/urllib/request.py", line 472, in open
    response = meth(req, response)
  File "/usr/lib/python3.5/urllib/request.py", line 582, in http_response
    'http', request, response, code, msg, hdrs)
  File "/usr/lib/python3.5/urllib/request.py", line 510, in error
    return self._call_chain(*args)
  File "/usr/lib/python3.5/urllib/request.py", line 444, in _call_chain
    result = func(*args)
  File "/usr/lib/python3.5/urllib/request.py", line 590, in http_error_default
    raise HTTPError(req.full_url, code, msg, hdrs, fp)
urllib.error.HTTPError: HTTP Error 404: Not Found

[INFO] (paasta-tools) This package is up to date.
[INFO] (paaster) This package is up to date.
[INFO] (pabiana) This package is up to date.
[INFO] (pablo) This package is up to date.
[ERROR] (pac) This package does not have downloadable releases.
[INFO] (pac-tool) This package is up to date.
[INFO] (pacal) This package is up to date.
[INFO] (pacbayesiannmf) This package is up to date.
[INFO] (pacbum) This package is up to date.
[INFO] (pace) This package is up to date.
[INFO] (paced) This package is up to date.
[INFO] (pacer) This package is up to date.
[INFO] (pacer-lib) This package is up to date.
[INFO] (pacer-scraper-library) This package is up to date.
[INFO] (pacha) This package is up to date.
[INFO] (pachi-py) This package is up to date.
[INFO] (pachinmypackage) This package is up to date.
[INFO] (pachong) This package is up to date.
[INFO] (pachy) This package is up to date.
[INFO] (paci) This package is up to date.
[INFO] (pacific) This package is up to date.
[INFO] (pacifica-configparser) This package is up to date.
[ERROR] (pack) This package does not have downloadable releases.
[INFO] (pack-command) This package is up to date.
[INFO] (pack64) This package is up to date.
[INFO] (package) This package is up to date.
[INFO] (package-archetype) This package is up to date.
[INFO] (package-boilerplate) This package is up to date.
[INFO] (package-cache) This package is up to date.
[INFO] (package-client) This package is up to date.
[INFO] (package-example) This package is up to date.
[INFO] (package-generator) This package is up to date.
[INFO] (package-install-check) This package is up to date.
[INFO] (package-json) This package is up to date.
[ERROR] (package-maker) This package does not have downloadable releases.
[ERROR] (package-manager) This package does not have downloadable releases.
[INFO] (package-name) This package is up to date.
[INFO] (package-oncom) This package is up to date.
[INFO] (package-pertama) This package is up to date.
[ERROR] (package-quality) This package does not have downloadable releases.
[INFO] (package-server) This package is up to date.
[INFO] (package-test) This package is up to date.
[INFO] (package-test-2298) This package is up to date.
[INFO] (package-test-bjl) This package is up to date.
[INFO] (package-test-x) This package is up to date.
[ERROR] (package-tool) This package does not have downloadable releases.
[INFO] (package-version) This package is up to date.
[INFO] (package-versions) This package is up to date.
[ERROR] (package1) Could not get a response from API for this package. See below for details.
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/pypicontents/api/pypi.py", line 264, in get_pkgdata
    timeout=10).read()
  File "/usr/lib/python3.5/urllib/request.py", line 163, in urlopen
    return opener.open(url, data, timeout)
  File "/usr/lib/python3.5/urllib/request.py", line 472, in open
    response = meth(req, response)
  File "/usr/lib/python3.5/urllib/request.py", line 582, in http_response
    'http', request, response, code, msg, hdrs)
  File "/usr/lib/python3.5/urllib/request.py", line 510, in error
    return self._call_chain(*args)
  File "/usr/lib/python3.5/urllib/request.py", line 444, in _call_chain
    result = func(*args)
  File "/usr/lib/python3.5/urllib/request.py", line 590, in http_error_default
    raise HTTPError(req.full_url, code, msg, hdrs, fp)
urllib.error.HTTPError: HTTP Error 404: Not Found

[INFO] (package2) This package is up to date.
[INFO] (packagecloud-poll) This package is up to date.
[INFO] (packagecloud-test) This package is up to date.
[INFO] (packagecore) This package is up to date.
[INFO] (packagedb-cli) This package is up to date.
[INFO] (packagedemo) This package is up to date.
[INFO] (packagedemo-liyaoyang) This package is up to date.
[INFO] (packagedeployment) This package is up to date.
[ERROR] (packageenv) This package does not have downloadable releases.
[INFO] (packagejn) This package is up to date.
[INFO] (packagejson) This package is up to date.
[INFO] (packagemanifest) This package is up to date.
[INFO] (packagemteszt01) This package is up to date.
[INFO] (packagemteszt02) This package is up to date.
[ERROR] (packagename) This package does not have downloadable releases.
[INFO] (packager) This package is up to date.
[INFO] (packageskel) This package is up to date.
[INFO] (packagesubnet) This package is up to date.
[INFO] (packagetest) This package is up to date.
[ERROR] (packagetest10) Could not get a response from API for this package. See below for details.
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/pypicontents/api/pypi.py", line 264, in get_pkgdata
    timeout=10).read()
  File "/usr/lib/python3.5/urllib/request.py", line 163, in urlopen
    return opener.open(url, data, timeout)
  File "/usr/lib/python3.5/urllib/request.py", line 472, in open
    response = meth(req, response)
  File "/usr/lib/python3.5/urllib/request.py", line 582, in http_response
    'http', request, response, code, msg, hdrs)
  File "/usr/lib/python3.5/urllib/request.py", line 510, in error
    return self._call_chain(*args)
  File "/usr/lib/python3.5/urllib/request.py", line 444, in _call_chain
    result = func(*args)
  File "/usr/lib/python3.5/urllib/request.py", line 590, in http_error_default
    raise HTTPError(req.full_url, code, msg, hdrs, fp)
urllib.error.HTTPError: HTTP Error 404: Not Found

[INFO] (packagetest105) This package is up to date.
[INFO] (packagetest106) This package is up to date.
[ERROR] (packagetest11) Could not get a response from API for this package. See below for details.
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/pypicontents/api/pypi.py", line 264, in get_pkgdata
    timeout=10).read()
  File "/usr/lib/python3.5/urllib/request.py", line 163, in urlopen
    return opener.open(url, data, timeout)
  File "/usr/lib/python3.5/urllib/request.py", line 472, in open
    response = meth(req, response)
  File "/usr/lib/python3.5/urllib/request.py", line 582, in http_response
    'http', request, response, code, msg, hdrs)
  File "/usr/lib/python3.5/urllib/request.py", line 510, in error
    return self._call_chain(*args)
  File "/usr/lib/python3.5/urllib/request.py", line 444, in _call_chain
    result = func(*args)
  File "/usr/lib/python3.5/urllib/request.py", line 590, in http_error_default
    raise HTTPError(req.full_url, code, msg, hdrs, fp)
urllib.error.HTTPError: HTTP Error 404: Not Found

[ERROR] (packagetest12) Could not get a response from API for this package. See below for details.
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/pypicontents/api/pypi.py", line 264, in get_pkgdata
    timeout=10).read()
  File "/usr/lib/python3.5/urllib/request.py", line 163, in urlopen
    return opener.open(url, data, timeout)
  File "/usr/lib/python3.5/urllib/request.py", line 472, in open
    response = meth(req, response)
  File "/usr/lib/python3.5/urllib/request.py", line 582, in http_response
    'http', request, response, code, msg, hdrs)
  File "/usr/lib/python3.5/urllib/request.py", line 510, in error
    return self._call_chain(*args)
  File "/usr/lib/python3.5/urllib/request.py", line 444, in _call_chain
    result = func(*args)
  File "/usr/lib/python3.5/urllib/request.py", line 590, in http_error_default
    raise HTTPError(req.full_url, code, msg, hdrs, fp)
urllib.error.HTTPError: HTTP Error 404: Not Found

[ERROR] (packagetest13) Could not get a response from API for this package. See below for details.
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/pypicontents/api/pypi.py", line 264, in get_pkgdata
    timeout=10).read()
  File "/usr/lib/python3.5/urllib/request.py", line 163, in urlopen
    return opener.open(url, data, timeout)
  File "/usr/lib/python3.5/urllib/request.py", line 472, in open
    response = meth(req, response)
  File "/usr/lib/python3.5/urllib/request.py", line 582, in http_response
    'http', request, response, code, msg, hdrs)
  File "/usr/lib/python3.5/urllib/request.py", line 510, in error
    return self._call_chain(*args)
  File "/usr/lib/python3.5/urllib/request.py", line 444, in _call_chain
    result = func(*args)
  File "/usr/lib/python3.5/urllib/request.py", line 590, in http_error_default
    raise HTTPError(req.full_url, code, msg, hdrs, fp)
urllib.error.HTTPError: HTTP Error 404: Not Found

[ERROR] (packagetest14) Could not get a response from API for this package. See below for details.
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/pypicontents/api/pypi.py", line 264, in get_pkgdata
    timeout=10).read()
  File "/usr/lib/python3.5/urllib/request.py", line 163, in urlopen
    return opener.open(url, data, timeout)
  File "/usr/lib/python3.5/urllib/request.py", line 472, in open
    response = meth(req, response)
  File "/usr/lib/python3.5/urllib/request.py", line 582, in http_response
    'http', request, response, code, msg, hdrs)
  File "/usr/lib/python3.5/urllib/request.py", line 510, in error
    return self._call_chain(*args)
  File "/usr/lib/python3.5/urllib/request.py", line 444, in _call_chain
    result = func(*args)
  File "/usr/lib/python3.5/urllib/request.py", line 590, in http_error_default
    raise HTTPError(req.full_url, code, msg, hdrs, fp)
urllib.error.HTTPError: HTTP Error 404: Not Found

[ERROR] (packagetest15) Could not get a response from API for this package. See below for details.
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/pypicontents/api/pypi.py", line 264, in get_pkgdata
    timeout=10).read()
  File "/usr/lib/python3.5/urllib/request.py", line 163, in urlopen
    return opener.open(url, data, timeout)
  File "/usr/lib/python3.5/urllib/request.py", line 472, in open
    response = meth(req, response)
  File "/usr/lib/python3.5/urllib/request.py", line 582, in http_response
    'http', request, response, code, msg, hdrs)
  File "/usr/lib/python3.5/urllib/request.py", line 510, in error
    return self._call_chain(*args)
  File "/usr/lib/python3.5/urllib/request.py", line 444, in _call_chain
    result = func(*args)
  File "/usr/lib/python3.5/urllib/request.py", line 590, in http_error_default
    raise HTTPError(req.full_url, code, msg, hdrs, fp)
urllib.error.HTTPError: HTTP Error 404: Not Found

[ERROR] (packagetest16) Could not get a response from API for this package. See below for details.
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/pypicontents/api/pypi.py", line 264, in get_pkgdata
    timeout=10).read()
  File "/usr/lib/python3.5/urllib/request.py", line 163, in urlopen
    return opener.open(url, data, timeout)
  File "/usr/lib/python3.5/urllib/request.py", line 472, in open
    response = meth(req, response)
  File "/usr/lib/python3.5/urllib/request.py", line 582, in http_response
    'http', request, response, code, msg, hdrs)
  File "/usr/lib/python3.5/urllib/request.py", line 510, in error
    return self._call_chain(*args)
  File "/usr/lib/python3.5/urllib/request.py", line 444, in _call_chain
    result = func(*args)
  File "/usr/lib/python3.5/urllib/request.py", line 590, in http_error_default
    raise HTTPError(req.full_url, code, msg, hdrs, fp)
urllib.error.HTTPError: HTTP Error 404: Not Found

[ERROR] (packagetest17) Could not get a response from API for this package. See below for details.
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/pypicontents/api/pypi.py", line 264, in get_pkgdata
    timeout=10).read()
  File "/usr/lib/python3.5/urllib/request.py", line 163, in urlopen
    return opener.open(url, data, timeout)
  File "/usr/lib/python3.5/urllib/request.py", line 472, in open
    response = meth(req, response)
  File "/usr/lib/python3.5/urllib/request.py", line 582, in http_response
    'http', request, response, code, msg, hdrs)
  File "/usr/lib/python3.5/urllib/request.py", line 510, in error
    return self._call_chain(*args)
  File "/usr/lib/python3.5/urllib/request.py", line 444, in _call_chain
    result = func(*args)
  File "/usr/lib/python3.5/urllib/request.py", line 590, in http_error_default
    raise HTTPError(req.full_url, code, msg, hdrs, fp)
urllib.error.HTTPError: HTTP Error 404: Not Found

[ERROR] (packagetest18) Could not get a response from API for this package. See below for details.
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/pypicontents/api/pypi.py", line 264, in get_pkgdata
    timeout=10).read()
  File "/usr/lib/python3.5/urllib/request.py", line 163, in urlopen
    return opener.open(url, data, timeout)
  File "/usr/lib/python3.5/urllib/request.py", line 472, in open
    response = meth(req, response)
  File "/usr/lib/python3.5/urllib/request.py", line 582, in http_response
    'http', request, response, code, msg, hdrs)
  File "/usr/lib/python3.5/urllib/request.py", line 510, in error
    return self._call_chain(*args)
  File "/usr/lib/python3.5/urllib/request.py", line 444, in _call_chain
    result = func(*args)
  File "/usr/lib/python3.5/urllib/request.py", line 590, in http_error_default
    raise HTTPError(req.full_url, code, msg, hdrs, fp)
urllib.error.HTTPError: HTTP Error 404: Not Found

[ERROR] (packagetest25) Could not get a response from API for this package. See below for details.
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/pypicontents/api/pypi.py", line 264, in get_pkgdata
    timeout=10).read()
  File "/usr/lib/python3.5/urllib/request.py", line 163, in urlopen
    return opener.open(url, data, timeout)
  File "/usr/lib/python3.5/urllib/request.py", line 472, in open
    response = meth(req, response)
  File "/usr/lib/python3.5/urllib/request.py", line 582, in http_response
    'http', request, response, code, msg, hdrs)
  File "/usr/lib/python3.5/urllib/request.py", line 510, in error
    return self._call_chain(*args)
  File "/usr/lib/python3.5/urllib/request.py", line 444, in _call_chain
    result = func(*args)
  File "/usr/lib/python3.5/urllib/request.py", line 590, in http_error_default
    raise HTTPError(req.full_url, code, msg, hdrs, fp)
urllib.error.HTTPError: HTTP Error 404: Not Found

[ERROR] (packagetest30) Could not get a response from API for this package. See below for details.
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/pypicontents/api/pypi.py", line 264, in get_pkgdata
    timeout=10).read()
  File "/usr/lib/python3.5/urllib/request.py", line 163, in urlopen
    return opener.open(url, data, timeout)
  File "/usr/lib/python3.5/urllib/request.py", line 472, in open
    response = meth(req, response)
  File "/usr/lib/python3.5/urllib/request.py", line 582, in http_response
    'http', request, response, code, msg, hdrs)
  File "/usr/lib/python3.5/urllib/request.py", line 510, in error
    return self._call_chain(*args)
  File "/usr/lib/python3.5/urllib/request.py", line 444, in _call_chain
    result = func(*args)
  File "/usr/lib/python3.5/urllib/request.py", line 590, in http_error_default
    raise HTTPError(req.full_url, code, msg, hdrs, fp)
urllib.error.HTTPError: HTTP Error 404: Not Found

[ERROR] (packagetest35) Could not get a response from API for this package. See below for details.
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/pypicontents/api/pypi.py", line 264, in get_pkgdata
    timeout=10).read()
  File "/usr/lib/python3.5/urllib/request.py", line 163, in urlopen
    return opener.open(url, data, timeout)
  File "/usr/lib/python3.5/urllib/request.py", line 472, in open
    response = meth(req, response)
  File "/usr/lib/python3.5/urllib/request.py", line 582, in http_response
    'http', request, response, code, msg, hdrs)
  File "/usr/lib/python3.5/urllib/request.py", line 510, in error
    return self._call_chain(*args)
  File "/usr/lib/python3.5/urllib/request.py", line 444, in _call_chain
    result = func(*args)
  File "/usr/lib/python3.5/urllib/request.py", line 590, in http_error_default
    raise HTTPError(req.full_url, code, msg, hdrs, fp)
urllib.error.HTTPError: HTTP Error 404: Not Found

[ERROR] (packagetest40) Could not get a response from API for this package. See below for details.
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/pypicontents/api/pypi.py", line 264, in get_pkgdata
    timeout=10).read()
  File "/usr/lib/python3.5/urllib/request.py", line 163, in urlopen
    return opener.open(url, data, timeout)
  File "/usr/lib/python3.5/urllib/request.py", line 472, in open
    response = meth(req, response)
  File "/usr/lib/python3.5/urllib/request.py", line 582, in http_response
    'http', request, response, code, msg, hdrs)
  File "/usr/lib/python3.5/urllib/request.py", line 510, in error
    return self._call_chain(*args)
  File "/usr/lib/python3.5/urllib/request.py", line 444, in _call_chain
    result = func(*args)
  File "/usr/lib/python3.5/urllib/request.py", line 590, in http_error_default
    raise HTTPError(req.full_url, code, msg, hdrs, fp)
urllib.error.HTTPError: HTTP Error 404: Not Found

[ERROR] (packagetest45) Could not get a response from API for this package. See below for details.
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/pypicontents/api/pypi.py", line 264, in get_pkgdata
    timeout=10).read()
  File "/usr/lib/python3.5/urllib/request.py", line 163, in urlopen
    return opener.open(url, data, timeout)
  File "/usr/lib/python3.5/urllib/request.py", line 472, in open
    response = meth(req, response)
  File "/usr/lib/python3.5/urllib/request.py", line 582, in http_response
    'http', request, response, code, msg, hdrs)
  File "/usr/lib/python3.5/urllib/request.py", line 510, in error
    return self._call_chain(*args)
  File "/usr/lib/python3.5/urllib/request.py", line 444, in _call_chain
    result = func(*args)
  File "/usr/lib/python3.5/urllib/request.py", line 590, in http_error_default
    raise HTTPError(req.full_url, code, msg, hdrs, fp)
urllib.error.HTTPError: HTTP Error 404: Not Found

[INFO] (packagetest50) This package is up to date.
[INFO] (packagetest55) This package is up to date.
[INFO] (packagetest60) This package is up to date.
[INFO] (packagetest65) This package is up to date.
[INFO] (packagetest70) This package is up to date.
[INFO] (packagetest75) This package is up to date.
[INFO] (packagetest80) This package is up to date.
[INFO] (packagetest85) This package is up to date.
[INFO] (packagetest90) This package is up to date.
[INFO] (packagetest95) This package is up to date.
[INFO] (packagetestpublishinghaha) This package is up to date.
[INFO] (packagetime) This package is up to date.
[INFO] (packagetools) This package is up to date.
[INFO] (packagetrack) This package is up to date.
[INFO] (packageurl-python) This package is up to date.
[INFO] (packageversion) This package is up to date.
[ERROR] (packaginator) Could not get a response from API for this package. See below for details.
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/pypicontents/api/pypi.py", line 264, in get_pkgdata
    timeout=10).read()
  File "/usr/lib/python3.5/urllib/request.py", line 163, in urlopen
    return opener.open(url, data, timeout)
  File "/usr/lib/python3.5/urllib/request.py", line 472, in open
    response = meth(req, response)
  File "/usr/lib/python3.5/urllib/request.py", line 582, in http_response
    'http', request, response, code, msg, hdrs)
  File "/usr/lib/python3.5/urllib/request.py", line 504, in error
    result = self._call_chain(*args)
  File "/usr/lib/python3.5/urllib/request.py", line 444, in _call_chain
    result = func(*args)
  File "/usr/lib/python3.5/urllib/request.py", line 696, in http_error_302
    return self.parent.open(new, timeout=req.timeout)
  File "/usr/lib/python3.5/urllib/request.py", line 472, in open
    response = meth(req, response)
  File "/usr/lib/python3.5/urllib/request.py", line 582, in http_response
    'http', request, response, code, msg, hdrs)
  File "/usr/lib/python3.5/urllib/request.py", line 510, in error
    return self._call_chain(*args)
  File "/usr/lib/python3.5/urllib/request.py", line 444, in _call_chain
    result = func(*args)
  File "/usr/lib/python3.5/urllib/request.py", line 590, in http_error_default
    raise HTTPError(req.full_url, code, msg, hdrs, fp)
urllib.error.HTTPError: HTTP Error 404: Not Found

[INFO] (packaging) This package is up to date.
[INFO] (packaging-python-tuto-guillaume) This package is up to date.
[INFO] (packbits) This package is up to date.
[ERROR] (packdeps) This package does not have downloadable releases.
[INFO] (packeges-test) This package is up to date.
[INFO] (packemo) This package is up to date.
[INFO] (packer) This package is up to date.
[INFO] (packer-cli) This package is up to date.
[INFO] (packer-py) This package is up to date.
[INFO] (packerinspector-api) This package is up to date.
[INFO] (packerlicious) This package is up to date.
[INFO] (packermate) This package is up to date.
[INFO] (packers) This package is up to date.
[INFO] (packet) This package is up to date.
[INFO] (packet-python) This package is up to date.
[INFO] (packetary) This package is up to date.
[INFO] (packetessentials) This package is up to date.
[INFO] (packetmq) This package is up to date.
[INFO] (packetreader) This package is up to date.
[INFO] (packets) This package is up to date.
[INFO] (packetseq) This package is up to date.
[INFO] (packety) This package is up to date.
[INFO] (packhalp) This package is up to date.
[INFO] (packilog) This package is up to date.
[ERROR] (packing) This package does not have downloadable releases.
[INFO] (packingslip) This package is up to date.
[ERROR] (packingtape) This package does not have downloadable releases.
[INFO] (packit) This package is up to date.
[INFO] (packjackn) This package is up to date.
[INFO] (packman) This package is up to date.
[INFO] (packmap) This package is up to date.
[INFO] (packone) This package is up to date.
[ERROR] (packpeto) This package does not have downloadable releases.
[INFO] (packrat) This package is up to date.
[INFO] (packsible) This package is up to date.
[INFO] (packspec) This package is up to date.
[INFO] (packstrap) This package is up to date.
[INFO] (packthing) This package is up to date.
[INFO] (packtivity) This package is up to date.
[INFO] (packtivity-kube-plugin) This package is up to date.
[INFO] (packtools) This package is up to date.
[INFO] (packtrack) This package is up to date.
[INFO] (packtree) This package is up to date.
[INFO] (packy-agent) This package is up to date.
[INFO] (packyou) This package is up to date.
[INFO] (paclair) This package is up to date.
[INFO] (pacli) This package is up to date.
[ERROR] (pacman) This package does not have downloadable releases.
[INFO] (pacman-game) This package is up to date.
[INFO] (pacmanprogressbar) This package is up to date.
[INFO] (pacmimi) This package is up to date.
[INFO] (paco) This package is up to date.
[INFO] (pacorm) This package is up to date.
[INFO] (pacparser) This package is up to date.
[INFO] (pacpy) This package is up to date.
[INFO] (pacsquery) This package is up to date.
[INFO] (pacsretrieve) This package is up to date.
[INFO] (pact) This package is up to date.
[INFO] (pact-broker-client) This package is up to date.
[INFO] (pact-python) This package is up to date.
[INFO] (pact-test) This package is up to date.
[INFO] (pactivitystream) This package is up to date.
[INFO] (pactool) This package is up to date.
[INFO] (pactors) This package is up to date.
[INFO] (pactum) This package is up to date.
[ERROR] (pad) This package does not have downloadable releases.
[INFO] (pad-on-left) This package is up to date.
[INFO] (pad-to-left) This package is up to date.
[INFO] (pad4pi) This package is up to date.
[INFO] (padaos) This package is up to date.
[INFO] (padar) This package is up to date.
[INFO] (padar-converter) This package is up to date.
[INFO] (padar-features) This package is up to date.
[INFO] (padar-realtime) This package is up to date.
[INFO] (padasip) This package is up to date.
[INFO] (padatious) This package is up to date.
[INFO] (padded-sel) This package is up to date.
[INFO] (padding) This package is up to date.
[INFO] (paddingoracle) This package is up to date.
[ERROR] (paddington) This package does not have downloadable releases.
[INFO] (paddle) This package is up to date.
[INFO] (paddlepaddle) This package is up to date.
[INFO] (paddlepaddle-gpu) This package is up to date.
[INFO] (pade) This package is up to date.
[INFO] (padje) This package is up to date.
[INFO] (padlang) This package is up to date.
[INFO] (padlock) This package is up to date.
[INFO] (padme) This package is up to date.
[INFO] (padmet) This package is up to date.
[INFO] (padova) This package is up to date.
[INFO] (padr) This package is up to date.
[INFO] (padre) This package is up to date.
[INFO] (pads) This package is up to date.
[INFO] (padsniff) This package is up to date.
[INFO] (padtools) This package is up to date.
[INFO] (padua) This package is up to date.
[INFO] (paegan) This package is up to date.
[INFO] (paegan-transport) This package is up to date.
[INFO] (paegan-viz) This package is up to date.
[ERROR] (paf) Could not extract data from this package. See below for details.
".php" extension not supported.
[INFO] (pafit) This package is up to date.
[ERROR] (pafo) Could not extract data from this package. See below for details.
Could not extract tarball. See below for details.
Traceback (most recent call last):
  File "/usr/lib/python3.5/tarfile.py", line 1631, in gzopen
    t = cls.taropen(name, mode, fileobj, **kwargs)
  File "/usr/lib/python3.5/tarfile.py", line 1607, in taropen
    return cls(name, mode, fileobj, **kwargs)
  File "/usr/lib/python3.5/tarfile.py", line 1470, in __init__
    self.firstmember = self.next()
  File "/usr/lib/python3.5/tarfile.py", line 2281, in next
    tarinfo = self.tarinfo.fromtarfile(self)
  File "/usr/lib/python3.5/tarfile.py", line 1082, in fromtarfile
    buf = tarfile.fileobj.read(BLOCKSIZE)
  File "/usr/lib/python3.5/gzip.py", line 274, in read
    return self._buffer.read(size)
  File "/usr/lib/python3.5/_compression.py", line 68, in readinto
    data = self.read(len(byte_view))
  File "/usr/lib/python3.5/gzip.py", line 461, in read
    if not self._read_gzip_header():
  File "/usr/lib/python3.5/gzip.py", line 409, in _read_gzip_header
    raise OSError('Not a gzipped file (%r)' % magic)
OSError: Not a gzipped file (b'<!')

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/pypicontents/api/pypi.py", line 131, in get_tar_topdir
    with closing(compressed(tarpath, tarmode)) as tar:
  File "/usr/lib/python3.5/tarfile.py", line 1577, in open
    return func(name, filemode, fileobj, **kwargs)
  File "/usr/lib/python3.5/tarfile.py", line 1635, in gzopen
    raise ReadError("not a gzip file")
tarfile.ReadError: not a gzip file

[INFO] (pafy) This package is up to date.
[INFO] (pag) This package is up to date.
[INFO] (pagan) This package is up to date.
[INFO] (paganini) This package is up to date.
[INFO] (pagarme-py) This package is up to date.
[INFO] (pagarme-python) This package is up to date.
[INFO] (pagarmepy) This package is up to date.
[INFO] (pagd) This package is up to date.
[INFO] (page) This package is up to date.
[INFO] (page-block) This package is up to date.
[INFO] (page-clustering) This package is up to date.
[INFO] (page-counter) This package is up to date.
[INFO] (page-finder) This package is up to date.
[INFO] (page-monitor) This package is up to date.
[INFO] (page-object) This package is up to date.
[INFO] (page-objects) This package is up to date.
[INFO] (page-scrapers) This package is up to date.
[INFO] (page-tracker) This package is up to date.
[INFO] (page38) This package is up to date.
[INFO] (pagecache) This package is up to date.
[INFO] (pagecalc) This package is up to date.
[ERROR] (pagediterator) This package does not have downloadable releases.
[INFO] (pagegen) This package is up to date.
[INFO] (pageinfo) This package is up to date.
[INFO] (pageit) This package is up to date.
[INFO] (pageobject) This package is up to date.
[INFO] (pageone) This package is up to date.
[INFO] (pagepress) This package is up to date.
[INFO] (pager) This package is up to date.
[INFO] (pagerange) This package is up to date.
[INFO] (pagerank) This package is up to date.
[INFO] (pagerator) This package is up to date.
[INFO] (pagerduty) This package is up to date.
[INFO] (pagerduty-api) This package is up to date.
[INFO] (pagerduty-events-api) This package is up to date.
[INFO] (pagerduty-trigger) This package is up to date.
[INFO] (pagerduty2splunk) This package is up to date.
[INFO] (pagerdutyapi) This package is up to date.
[INFO] (pagerdutyduty) This package is up to date.
[INFO] (pagerdutystats) This package is up to date.
[INFO] (pagerunit) This package is up to date.
[ERROR] (pages) This package does not have downloadable releases.
[INFO] (pageshot) This package is up to date.
[INFO] (pagespeedwrapper) This package is up to date.
[INFO] (pagetracker) This package is up to date.
[INFO] (pagetree) This package is up to date.
[INFO] (pageup) This package is up to date.
[INFO] (pageview-client) This package is up to date.
[INFO] (pageviewapi) This package is up to date.
[INFO] (pageviewcount) This package is up to date.
[INFO] (paginate) This package is up to date.
[INFO] (paginate-sqlalchemy) This package is up to date.
[INFO] (paginate-whoosh) This package is up to date.
[INFO] (paginate-wrapper) This package is up to date.
[INFO] (paginatify) This package is up to date.
[INFO] (paginatify-elasticsearch-dsl) This package is up to date.
[INFO] (paginatify-sqlalchemy) This package is up to date.
[INFO] (paginator) This package is up to date.
[INFO] (pagingish) This package is up to date.
[INFO] (pagingserver) This package is up to date.
[INFO] (pagoda) This package is up to date.
[INFO] (pagosonline) This package is up to date.
[ERROR] (pagrant) This package does not have downloadable releases.
[INFO] (pagseguro) This package is up to date.
[INFO] (pagseguro-api-v2) This package is up to date.
[INFO] (pagseguro-python) This package is up to date.
[INFO] (pagseguro-sdk) This package is up to date.
[INFO] (pagseguro-xml) This package is up to date.
[INFO] (pagure-dist-git) This package is up to date.
[ERROR] (pagure-importer) This package does not have downloadable releases.
[INFO] (pahelee) This package is up to date.
[INFO] (paho-mqtt) This package is up to date.
[INFO] (pahomqtt) This package is up to date.
[ERROR] (pai-db) This package does not have downloadable releases.
[ERROR] (pai-lang) This package does not have downloadable releases.
[INFO] (pai-parser) This package is up to date.
[INFO] (paicli) This package is up to date.
[ERROR] (paida) Could not extract data from this package. See below for details.
".php" extension not supported.
[INFO] (paiflow) This package is up to date.
[INFO] (pail) This package is up to date.
[ERROR] (paimei) This package does not have downloadable releases.
[INFO] (pain) This package is up to date.
[INFO] (painless-sqlalchemy) This package is up to date.
[INFO] (paint) This package is up to date.
[INFO] (painted-word) This package is up to date.
[INFO] (painter) This package is up to date.
[INFO] (painterm) This package is up to date.
[INFO] (paintpartners) This package is up to date.
[INFO] (paipa) This package is up to date.
[INFO] (paipy) This package is up to date.
[INFO] (pair) This package is up to date.
[INFO] (pair-fastq) This package is up to date.
[INFO] (paired) This package is up to date.
[INFO] (paired-end-debarcoder) This package is up to date.
[ERROR] (paired-sequence-utils) Could not get a response from API for this package. See below for details.
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/pypicontents/api/pypi.py", line 264, in get_pkgdata
    timeout=10).read()
  File "/usr/lib/python3.5/urllib/request.py", line 163, in urlopen
    return opener.open(url, data, timeout)
  File "/usr/lib/python3.5/urllib/request.py", line 472, in open
    response = meth(req, response)
  File "/usr/lib/python3.5/urllib/request.py", line 582, in http_response
    'http', request, response, code, msg, hdrs)
  File "/usr/lib/python3.5/urllib/request.py", line 504, in error
    result = self._call_chain(*args)
  File "/usr/lib/python3.5/urllib/request.py", line 444, in _call_chain
    result = func(*args)
  File "/usr/lib/python3.5/urllib/request.py", line 696, in http_error_302
    return self.parent.open(new, timeout=req.timeout)
  File "/usr/lib/python3.5/urllib/request.py", line 472, in open
    response = meth(req, response)
  File "/usr/lib/python3.5/urllib/request.py", line 582, in http_response
    'http', request, response, code, msg, hdrs)
  File "/usr/lib/python3.5/urllib/request.py", line 510, in error
    return self._call_chain(*args)
  File "/usr/lib/python3.5/urllib/request.py", line 444, in _call_chain
    result = func(*args)
  File "/usr/lib/python3.5/urllib/request.py", line 590, in http_error_default
    raise HTTPError(req.full_url, code, msg, hdrs, fp)
urllib.error.HTTPError: HTTP Error 404: Not Found

[INFO] (pairing) This package is up to date.
[INFO] (pairlist) This package is up to date.
[INFO] (pairplotr) This package is up to date.
[INFO] (pairs2groups) This package is up to date.
[INFO] (pairtools) This package is up to date.
[INFO] (pairtree) This package is up to date.
[INFO] (pairwise) This package is up to date.
[INFO] (paisley) This package is up to date.
[ERROR] (pak) Could not get a response from API for this package. See below for details.
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/pypicontents/api/pypi.py", line 264, in get_pkgdata
    timeout=10).read()
  File "/usr/lib/python3.5/urllib/request.py", line 163, in urlopen
    return opener.open(url, data, timeout)
  File "/usr/lib/python3.5/urllib/request.py", line 472, in open
    response = meth(req, response)
  File "/usr/lib/python3.5/urllib/request.py", line 582, in http_response
    'http', request, response, code, msg, hdrs)
  File "/usr/lib/python3.5/urllib/request.py", line 510, in error
    return self._call_chain(*args)
  File "/usr/lib/python3.5/urllib/request.py", line 444, in _call_chain
    result = func(*args)
  File "/usr/lib/python3.5/urllib/request.py", line 590, in http_error_default
    raise HTTPError(req.full_url, code, msg, hdrs, fp)
urllib.error.HTTPError: HTTP Error 404: Not Found

[INFO] (paka-breadcrumbs) This package is up to date.
[INFO] (paka-cmark) This package is up to date.
[INFO] (paka-feedgenerator) This package is up to date.
[INFO] (paka-funcreg) This package is up to date.
[INFO] (paka-sitemaps) This package is up to date.
[INFO] (paka-vx1) This package is up to date.
[INFO] (paka-webstatic) This package is up to date.
[ERROR] (pake) This package does not have downloadable releases.
[INFO] (paketimiz) This package is up to date.
[INFO] (pakettikauppa) This package is up to date.
[INFO] (pakit) This package is up to date.
[INFO] (pakker) This package is up to date.
[INFO] (pakrat) This package is up to date.
[ERROR] (pal) This package does not have downloadable releases.
[INFO] (pal2) This package is up to date.
[INFO] (palabra) This package is up to date.
[ERROR] (palabre) Could not extract data from this package. See below for details.
This package download URL does not point to a valid file: "http://palabre.gavroche.net/content/view/15/28/"
[INFO] (paladin) This package is up to date.
[INFO] (palal) This package is up to date.
[INFO] (palantir-spark-time) This package is up to date.
[INFO] (palb) This package is up to date.
[INFO] (pale) This package is up to date.
[INFO] (paleomix) This package is up to date.
[INFO] (palettable) This package is up to date.
[INFO] (palette) This package is up to date.
[INFO] (palette-detect) This package is up to date.
[ERROR] (paletteextractor) This package does not have downloadable releases.
[INFO] (palin) This package is up to date.
[INFO] (palindrome) This package is up to date.
[INFO] (palindromus) This package is up to date.
[INFO] (palladio) This package is up to date.
[INFO] (palladium) This package is up to date.
[ERROR] (pallet) Could not get a response from API for this package. See below for details.
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/pypicontents/api/pypi.py", line 264, in get_pkgdata
    timeout=10).read()
  File "/usr/lib/python3.5/urllib/request.py", line 163, in urlopen
    return opener.open(url, data, timeout)
  File "/usr/lib/python3.5/urllib/request.py", line 472, in open
    response = meth(req, response)
  File "/usr/lib/python3.5/urllib/request.py", line 582, in http_response
    'http', request, response, code, msg, hdrs)
  File "/usr/lib/python3.5/urllib/request.py", line 510, in error
    return self._call_chain(*args)
  File "/usr/lib/python3.5/urllib/request.py", line 444, in _call_chain
    result = func(*args)
  File "/usr/lib/python3.5/urllib/request.py", line 590, in http_error_default
    raise HTTPError(req.full_url, code, msg, hdrs, fp)
urllib.error.HTTPError: HTTP Error 404: Not Found

[ERROR] (pallet-tool) This package does not have downloadable releases.
[INFO] (palletier) This package is up to date.
[INFO] (palletize) This package is up to date.
[INFO] (pallets-sphinx-themes) This package is up to date.
[INFO] (pallium) This package is up to date.
[INFO] (pallium-rpc) This package is up to date.
[INFO] (palm) This package is up to date.
[INFO] (palm2vcal) This package is up to date.
[ERROR] (palmdb) This package does not have downloadable releases.
[INFO] (palmer) This package is up to date.
[INFO] (palmettopy) This package is up to date.
[ERROR] (paloma) Could not extract data from this package. See below for details.
".php" extension not supported.
[INFO] (palpatine) This package is up to date.
[INFO] (palpg) This package is up to date.
[INFO] (palpy) This package is up to date.
[INFO] (palpyutil) This package is up to date.
[INFO] (palu) This package is up to date.
[INFO] (paludis-resolve-summary) This package is up to date.
[ERROR] (palvac-haha) This package does not have downloadable releases.
[INFO] (palvin) This package is up to date.
[INFO] (pam) This package is up to date.
[INFO] (pam-py-linotp) This package is up to date.
[INFO] (pam-yubico) This package is up to date.
[ERROR] (pam3) This package does not have downloadable releases.
[INFO] (pamagent) This package is up to date.
[ERROR] (pambox) This package does not have downloadable releases.
[INFO] (pame) This package is up to date.
[INFO] (pamela) This package is up to date.
[INFO] (pametis) This package is up to date.
[INFO] (pamixer) This package is up to date.
[INFO] (paml) This package is up to date.
[INFO] (pammy) This package is up to date.
[INFO] (pammysqltools) This package is up to date.
[INFO] (pamphlet) This package is up to date.
[INFO] (pampio) This package is up to date.
[INFO] (pamqp) This package is up to date.
[INFO] (pan) This package is up to date.
[INFO] (pan-nester) This package is up to date.
[INFO] (pan-python) This package is up to date.
[INFO] (pan-readme) This package is up to date.
[INFO] (panacea) This package is up to date.
[INFO] (panache) This package is up to date.
[INFO] (panama) This package is up to date.
[INFO] (panasonic-viera) This package is up to date.
[INFO] (panavatar) This package is up to date.
[INFO] (pancake) This package is up to date.
[INFO] (pancakes) This package is up to date.
[INFO] (panci) This package is up to date.
[INFO] (pancircs) This package is up to date.
[INFO] (pancloud) This package is up to date.
[INFO] (pancritic) This package is up to date.
[INFO] (panda) This package is up to date.
[ERROR] (panda-black-test) This package does not have downloadable releases.
[INFO] (panda-client) This package is up to date.
[INFO] (panda-common-s) This package is up to date.
[INFO] (panda-example-django) This package is up to date.
[ERROR] (panda-wolfe) Could not get a response from API for this package. See below for details.
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/pypicontents/api/pypi.py", line 264, in get_pkgdata
    timeout=10).read()
  File "/usr/lib/python3.5/urllib/request.py", line 163, in urlopen
    return opener.open(url, data, timeout)
  File "/usr/lib/python3.5/urllib/request.py", line 472, in open
    response = meth(req, response)
  File "/usr/lib/python3.5/urllib/request.py", line 582, in http_response
    'http', request, response, code, msg, hdrs)
  File "/usr/lib/python3.5/urllib/request.py", line 510, in error
    return self._call_chain(*args)
  File "/usr/lib/python3.5/urllib/request.py", line 444, in _call_chain
    result = func(*args)
  File "/usr/lib/python3.5/urllib/request.py", line 590, in http_error_default
    raise HTTPError(req.full_url, code, msg, hdrs, fp)
urllib.error.HTTPError: HTTP Error 404: Not Found

[INFO] (panda3d) This package is up to date.
[INFO] (panda3d-inputmapper) This package is up to date.
[INFO] (panda3d-pman) This package is up to date.
[INFO] (pandac) This package is up to date.
[INFO] (pandacan) This package is up to date.
[INFO] (pandadocs) This package is up to date.
[INFO] (pandaemonium) This package is up to date.
[INFO] (pandahouse) This package is up to date.
[INFO] (pandalone) This package is up to date.
[INFO] (pandamonium) This package is up to date.
[INFO] (pandana) This package is up to date.
[INFO] (pandanas) This package is up to date.
[INFO] (pandapay) This package is up to date.
[INFO] (pandapower) This package is up to date.
[INFO] (pandarss) This package is up to date.
[INFO] (pandarus) This package is up to date.
[INFO] (pandarus-remote) This package is up to date.
[INFO] (pandas) This package is up to date.
[INFO] (pandas-access) This package is up to date.
[INFO] (pandas-bamboo) This package is up to date.
[INFO] (pandas-bj) This package is up to date.
[INFO] (pandas-charm) This package is up to date.
[INFO] (pandas-compat) This package is up to date.
[INFO] (pandas-confusion) This package is up to date.
[INFO] (pandas-custom-mask) This package is up to date.
[INFO] (pandas-datapackage-reader) This package is up to date.
[INFO] (pandas-datareader) This package is up to date.
[INFO] (pandas-datareader-gdax) This package is up to date.
[INFO] (pandas-datareaders-unofficial) This package is up to date.
[INFO] (pandas-degreedays) This package is up to date.
[ERROR] (pandas-diligent) This package does not have downloadable releases.
[INFO] (pandas-drf-tools) This package is up to date.
[INFO] (pandas-ext) This package is up to date.
[INFO] (pandas-files) This package is up to date.
[INFO] (pandas-finance) This package is up to date.
[INFO] (pandas-flavor) This package is up to date.
[INFO] (pandas-gbq) This package is up to date.
[INFO] (pandas-helpers) This package is up to date.
[INFO] (pandas-highcharts) This package is up to date.
[INFO] (pandas-interactive-html) This package is up to date.
[INFO] (pandas-io) This package is up to date.
[INFO] (pandas-jalali) This package is up to date.
[INFO] (pandas-linker) This package is up to date.
[INFO] (pandas-lite) This package is up to date.
[INFO] (pandas-mapper) This package is up to date.
[INFO] (pandas-market-calendars) This package is up to date.
[INFO] (pandas-mate) This package is up to date.
[INFO] (pandas-ml) This package is up to date.
[INFO] (pandas-montecarlo) This package is up to date.
[INFO] (pandas-msgpack) This package is up to date.
[INFO] (pandas-multi) This package is up to date.
[INFO] (pandas-multiprocess) This package is up to date.
[INFO] (pandas-multiprocessing) This package is up to date.
[INFO] (pandas-oracle) This package is up to date.
[INFO] (pandas-parallel) This package is up to date.
[INFO] (pandas-plink) This package is up to date.
[INFO] (pandas-ply) This package is up to date.
[INFO] (pandas-profiling) This package is up to date.
[INFO] (pandas-qt) This package is up to date.
[INFO] (pandas-redistrict) This package is up to date.
[INFO] (pandas-redshift) This package is up to date.
[INFO] (pandas-refract) This package is up to date.
[INFO] (pandas-rs) This package is up to date.
[INFO] (pandas-schema) This package is up to date.
[INFO] (pandas-sql) This package is up to date.
[INFO] (pandas-sql-wrapper) This package is up to date.
[INFO] (pandas-streaming) This package is up to date.
[INFO] (pandas-summary) This package is up to date.
[ERROR] (pandas-talib) This package does not have downloadable releases.
[INFO] (pandas-td) This package is up to date.
[INFO] (pandas-timeseries) This package is up to date.
[INFO] (pandas-transformers) This package is up to date.
[INFO] (pandas-validation) This package is up to date.
[INFO] (pandas-validator) This package is up to date.
[INFO] (pandas-vectors) This package is up to date.
[INFO] (pandas2) This package is up to date.
[INFO] (pandas2sklearn) This package is up to date.
[INFO] (pandas3js) This package is up to date.
[INFO] (pandascore) This package is up to date.
[INFO] (pandasdatareader) This package is up to date.
[INFO] (pandasdmx) This package is up to date.
[INFO] (pandasgbq) This package is up to date.
[WARNING] 
[WARNING] Processing has taken more than 2100 seconds. Interrupting.
[WARNING] Processing will continue in next iteration.
[WARNING] 
[INFO] 
[INFO] 
[INFO] Total packages: 22388
[INFO]     Packages processed: 631
[INFO]         Packages updated: 0
[INFO]         Packages up-to-date: 565
[INFO]         Packages without response: 21
[INFO]         Packages without urls: 0
[INFO]         Packages without downloads: 35
[INFO]         Packages with data errors: 10
[INFO]     Packages not processed: 21757
[INFO] 
[INFO] 
[INFO] Ending execution.
