[INFO] Starting execution.
[INFO] Downloading package list from PyPI ...
[ERROR] (n) This package does not have downloadable releases.
[INFO] (n-again) This package is up to date.
[INFO] (n-e-s-t-e-r-2017) This package is up to date.
[INFO] (n-log) This package is up to date.
[INFO] (n-property) This package is up to date.
[INFO] (n-way-cache) This package is up to date.
[INFO] (n1) This package is up to date.
[INFO] (n123ester) This package is up to date.
[INFO] (n2) This package is up to date.
[INFO] (n2-tools) This package is up to date.
[INFO] (n26) This package is up to date.
[INFO] (n2cw) This package is up to date.
[INFO] (n2w) This package is up to date.
[INFO] (n3d) This package is up to date.
[ERROR] (n8henrie) This package does not have downloadable releases.
[INFO] (n8scripts) This package is up to date.
[INFO] (na3x) This package is up to date.
[INFO] (naakh) This package is up to date.
[INFO] (naam) This package is up to date.
[INFO] (naan) This package is up to date.
[INFO] (naarad) This package is up to date.
[ERROR] (nabazpy) This package does not have downloadable releases.
[INFO] (nabirds) This package is up to date.
[INFO] (nabo) This package is up to date.
[INFO] (nac) This package is up to date.
[INFO] (nacculator) This package is up to date.
[INFO] (nacelle) This package is up to date.
[INFO] (nacha) This package is up to date.
[ERROR] (nacho) This package does not have downloadable releases.
[ERROR] (nacl) This package does not have downloadable releases.
[INFO] (naclautomake) This package is up to date.
[INFO] (nad-receiver) This package is up to date.
[INFO] (nada) This package is up to date.
[INFO] (nadamq) This package is up to date.
[INFO] (nadds) This package is up to date.
[INFO] (nadej) This package is up to date.
[INFO] (nadex) This package is up to date.
[INFO] (nadia) This package is up to date.
[INFO] (nadtcp) This package is up to date.
[INFO] (naeutils) This package is up to date.
[INFO] (naf) This package is up to date.
[INFO] (naf2conll) This package is up to date.
[INFO] (naffoliapy) This package is up to date.
[ERROR] (naftawayh) Could not get a response from API for this package. See below for details.
Traceback (most recent call last):
  File "/usr/lib/python3.5/urllib/request.py", line 1254, in do_open
    h.request(req.get_method(), req.selector, req.data, headers)
  File "/usr/lib/python3.5/http/client.py", line 1107, in request
    self._send_request(method, url, body, headers)
  File "/usr/lib/python3.5/http/client.py", line 1152, in _send_request
    self.endheaders(body)
  File "/usr/lib/python3.5/http/client.py", line 1103, in endheaders
    self._send_output(message_body)
  File "/usr/lib/python3.5/http/client.py", line 934, in _send_output
    self.send(msg)
  File "/usr/lib/python3.5/http/client.py", line 877, in send
    self.connect()
  File "/usr/lib/python3.5/http/client.py", line 1253, in connect
    super().connect()
  File "/usr/lib/python3.5/http/client.py", line 849, in connect
    (self.host,self.port), self.timeout, self.source_address)
  File "/usr/lib/python3.5/socket.py", line 712, in create_connection
    raise err
  File "/usr/lib/python3.5/socket.py", line 703, in create_connection
    sock.connect(sa)
OSError: [Errno 99] Cannot assign requested address

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/pypicontents/api/pypi.py", line 264, in get_pkgdata
    timeout=10).read()
  File "/usr/lib/python3.5/urllib/request.py", line 163, in urlopen
    return opener.open(url, data, timeout)
  File "/usr/lib/python3.5/urllib/request.py", line 472, in open
    response = meth(req, response)
  File "/usr/lib/python3.5/urllib/request.py", line 582, in http_response
    'http', request, response, code, msg, hdrs)
  File "/usr/lib/python3.5/urllib/request.py", line 504, in error
    result = self._call_chain(*args)
  File "/usr/lib/python3.5/urllib/request.py", line 444, in _call_chain
    result = func(*args)
  File "/usr/lib/python3.5/urllib/request.py", line 696, in http_error_302
    return self.parent.open(new, timeout=req.timeout)
  File "/usr/lib/python3.5/urllib/request.py", line 466, in open
    response = self._open(req, data)
  File "/usr/lib/python3.5/urllib/request.py", line 484, in _open
    '_open', req)
  File "/usr/lib/python3.5/urllib/request.py", line 444, in _call_chain
    result = func(*args)
  File "/usr/lib/python3.5/urllib/request.py", line 1297, in https_open
    context=self._context, check_hostname=self._check_hostname)
  File "/usr/lib/python3.5/urllib/request.py", line 1256, in do_open
    raise URLError(err)
urllib.error.URLError: <urlopen error [Errno 99] Cannot assign requested address>

[INFO] (naga) This package is up to date.
[INFO] (nagaconda) This package is up to date.
[ERROR] (nagalib) This package does not have downloadable releases.
[INFO] (nagaram) This package is up to date.
[INFO] (nagare) This package is up to date.
[INFO] (nagare-examples) This package is up to date.
[INFO] (nagare-ide) This package is up to date.
[INFO] (nagare-jquery) This package is up to date.
[INFO] (nagato) This package is up to date.
[INFO] (nagator) This package is up to date.
[INFO] (naghni) This package is up to date.
[INFO] (nagi) This package is up to date.
[INFO] (nagifo) This package is up to date.
[INFO] (nagii) This package is up to date.
[ERROR] (nagini) Could not get a response from API for this package. See below for details.
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/pypicontents/api/pypi.py", line 264, in get_pkgdata
    timeout=10).read()
  File "/usr/lib/python3.5/urllib/request.py", line 163, in urlopen
    return opener.open(url, data, timeout)
  File "/usr/lib/python3.5/urllib/request.py", line 472, in open
    response = meth(req, response)
  File "/usr/lib/python3.5/urllib/request.py", line 582, in http_response
    'http', request, response, code, msg, hdrs)
  File "/usr/lib/python3.5/urllib/request.py", line 510, in error
    return self._call_chain(*args)
  File "/usr/lib/python3.5/urllib/request.py", line 444, in _call_chain
    result = func(*args)
  File "/usr/lib/python3.5/urllib/request.py", line 590, in http_error_default
    raise HTTPError(req.full_url, code, msg, hdrs, fp)
urllib.error.HTTPError: HTTP Error 404: Not Found

[ERROR] (naginterfaces) Could not get a response from API for this package. See below for details.
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/pypicontents/api/pypi.py", line 264, in get_pkgdata
    timeout=10).read()
  File "/usr/lib/python3.5/urllib/request.py", line 163, in urlopen
    return opener.open(url, data, timeout)
  File "/usr/lib/python3.5/urllib/request.py", line 472, in open
    response = meth(req, response)
  File "/usr/lib/python3.5/urllib/request.py", line 582, in http_response
    'http', request, response, code, msg, hdrs)
  File "/usr/lib/python3.5/urllib/request.py", line 510, in error
    return self._call_chain(*args)
  File "/usr/lib/python3.5/urllib/request.py", line 444, in _call_chain
    result = func(*args)
  File "/usr/lib/python3.5/urllib/request.py", line 590, in http_error_default
    raise HTTPError(req.full_url, code, msg, hdrs, fp)
urllib.error.HTTPError: HTTP Error 404: Not Found

[INFO] (nagios) This package is up to date.
[INFO] (nagios-api) This package is up to date.
[INFO] (nagios-audit) This package is up to date.
[INFO] (nagios-check-hddtemp) This package is up to date.
[INFO] (nagios-check-supervisord) This package is up to date.
[INFO] (nagios-cloudwatch-plugin) This package is up to date.
[INFO] (nagios-elasticsearch) This package is up to date.
[INFO] (nagios-filecount-plugin) This package is up to date.
[INFO] (nagios-gearman-plugin) This package is up to date.
[INFO] (nagios-graphite) This package is up to date.
[INFO] (nagios-load-per-core) This package is up to date.
[INFO] (nagios-mesos) This package is up to date.
[INFO] (nagios-mesos-service-check) This package is up to date.
[INFO] (nagios-notification-google-calendar) This package is up to date.
[INFO] (nagios-notification-jabber) This package is up to date.
[INFO] (nagios-nsca) This package is up to date.
[INFO] (nagios-nvidia-smi-plugin) This package is up to date.
[INFO] (nagios-plugin-elasticsearch) This package is up to date.
[INFO] (nagios-rabbitmq-plugin) This package is up to date.
[INFO] (nagios-responsetime) This package is up to date.
[INFO] (nagios-sentry) This package is up to date.
[INFO] (nagios-sql) This package is up to date.
[INFO] (nagios-taskserver-plugin) This package is up to date.
[INFO] (nagios-unity) This package is up to date.
[INFO] (nagios2trac) This package is up to date.
[INFO] (nagioscheck) This package is up to date.
[INFO] (nagioscli) This package is up to date.
[INFO] (nagiosctl) This package is up to date.
[INFO] (nagiosharder) This package is up to date.
[INFO] (nagiosplugin) This package is up to date.
[INFO] (nagisa) This package is up to date.
[INFO] (nago) This package is up to date.
[ERROR] (nagobah) This package does not have downloadable releases.
[INFO] (nagobah-with-server) This package is up to date.
[INFO] (nagparser) This package is up to date.
[ERROR] (nagplug) Could not get a response from API for this package. See below for details.
Traceback (most recent call last):
  File "/usr/lib/python3.5/urllib/request.py", line 1254, in do_open
    h.request(req.get_method(), req.selector, req.data, headers)
  File "/usr/lib/python3.5/http/client.py", line 1107, in request
    self._send_request(method, url, body, headers)
  File "/usr/lib/python3.5/http/client.py", line 1152, in _send_request
    self.endheaders(body)
  File "/usr/lib/python3.5/http/client.py", line 1103, in endheaders
    self._send_output(message_body)
  File "/usr/lib/python3.5/http/client.py", line 934, in _send_output
    self.send(msg)
  File "/usr/lib/python3.5/http/client.py", line 877, in send
    self.connect()
  File "/usr/lib/python3.5/http/client.py", line 1253, in connect
    super().connect()
  File "/usr/lib/python3.5/http/client.py", line 849, in connect
    (self.host,self.port), self.timeout, self.source_address)
  File "/usr/lib/python3.5/socket.py", line 712, in create_connection
    raise err
  File "/usr/lib/python3.5/socket.py", line 703, in create_connection
    sock.connect(sa)
OSError: [Errno 99] Cannot assign requested address

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/pypicontents/api/pypi.py", line 264, in get_pkgdata
    timeout=10).read()
  File "/usr/lib/python3.5/urllib/request.py", line 163, in urlopen
    return opener.open(url, data, timeout)
  File "/usr/lib/python3.5/urllib/request.py", line 466, in open
    response = self._open(req, data)
  File "/usr/lib/python3.5/urllib/request.py", line 484, in _open
    '_open', req)
  File "/usr/lib/python3.5/urllib/request.py", line 444, in _call_chain
    result = func(*args)
  File "/usr/lib/python3.5/urllib/request.py", line 1297, in https_open
    context=self._context, check_hostname=self._check_hostname)
  File "/usr/lib/python3.5/urllib/request.py", line 1256, in do_open
    raise URLError(err)
urllib.error.URLError: <urlopen error [Errno 99] Cannot assign requested address>

[ERROR] (nagpy) Could not extract data from this package. See below for details.
"ftp://ftp.cdc.noaa.gov/Public/jsw/nagpy.tar.gz" file could not be downloaded. See below for details.
Traceback (most recent call last):
  File "/usr/lib/python3.5/urllib/request.py", line 1470, in ftp_open
    fw = self.connect_ftp(user, passwd, host, port, dirs, req.timeout)
  File "/usr/lib/python3.5/urllib/request.py", line 1492, in connect_ftp
    persistent=False)
  File "/usr/lib/python3.5/urllib/request.py", line 2313, in __init__
    self.init()
  File "/usr/lib/python3.5/urllib/request.py", line 2325, in init
    self.ftp.cwd(_target)
  File "/usr/lib/python3.5/ftplib.py", line 632, in cwd
    return self.voidcmd(cmd)
  File "/usr/lib/python3.5/ftplib.py", line 279, in voidcmd
    return self.voidresp()
  File "/usr/lib/python3.5/ftplib.py", line 252, in voidresp
    resp = self.getresp()
  File "/usr/lib/python3.5/ftplib.py", line 247, in getresp
    raise error_perm(resp)
ftplib.error_perm: 550 Failed to change directory.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/pypicontents/api/pypi.py", line 107, in download_tar
    f.write(urlopen(url=urlesc(pkgurl), timeout=10).read())
  File "/usr/lib/python3.5/urllib/request.py", line 163, in urlopen
    return opener.open(url, data, timeout)
  File "/usr/lib/python3.5/urllib/request.py", line 466, in open
    response = self._open(req, data)
  File "/usr/lib/python3.5/urllib/request.py", line 484, in _open
    '_open', req)
  File "/usr/lib/python3.5/urllib/request.py", line 444, in _call_chain
    result = func(*args)
  File "/usr/lib/python3.5/urllib/request.py", line 1488, in ftp_open
    raise exc.with_traceback(sys.exc_info()[2])
  File "/usr/lib/python3.5/urllib/request.py", line 1470, in ftp_open
    fw = self.connect_ftp(user, passwd, host, port, dirs, req.timeout)
  File "/usr/lib/python3.5/urllib/request.py", line 1492, in connect_ftp
    persistent=False)
  File "/usr/lib/python3.5/urllib/request.py", line 2313, in __init__
    self.init()
  File "/usr/lib/python3.5/urllib/request.py", line 2325, in init
    self.ftp.cwd(_target)
  File "/usr/lib/python3.5/ftplib.py", line 632, in cwd
    return self.voidcmd(cmd)
  File "/usr/lib/python3.5/ftplib.py", line 279, in voidcmd
    return self.voidresp()
  File "/usr/lib/python3.5/ftplib.py", line 252, in voidresp
    resp = self.getresp()
  File "/usr/lib/python3.5/ftplib.py", line 247, in getresp
    raise error_perm(resp)
urllib.error.URLError: <urlopen error ftp error: error_perm('550 Failed to change directory.',)>

[INFO] (nagpyrc) This package is up to date.
[INFO] (nahpackpy) This package is up to date.
[INFO] (nahum-debug-utils) This package is up to date.
[INFO] (naiad) This package is up to date.
[INFO] (nailbox) This package is up to date.
[INFO] (nailer) This package is up to date.
[INFO] (nailgun) This package is up to date.
[INFO] (nailgun-net-check) This package is up to date.
[INFO] (nailpack-flask) This package is up to date.
[INFO] (nails) This package is up to date.
[INFO] (naima) This package is up to date.
[INFO] (naive) This package is up to date.
[INFO] (naive-bayes) This package is up to date.
[INFO] (naivebayes) This package is up to date.
[INFO] (naivebayesclassifier) This package is up to date.
[INFO] (naivede) This package is up to date.
[INFO] (naivepool) This package is up to date.
[INFO] (naivepyrunner) This package is up to date.
[INFO] (naivetcp) This package is up to date.
[ERROR] (naja) Could not extract data from this package. See below for details.
This package download URL does not point to a valid file: "http://www.keyphrene.com/products/naja"
[INFO] (najdisi-sms) This package is up to date.
[INFO] (najha) This package is up to date.
[INFO] (nakadi-end2end) This package is up to date.
[INFO] (naked) This package is up to date.
[ERROR] (nakedplanning) This package does not have downloadable releases.
[INFO] (nakedrequests) This package is up to date.
[INFO] (nalaf) This package is up to date.
[INFO] (nalu) This package is up to date.
[INFO] (namae) This package is up to date.
[INFO] (namalizer) This package is up to date.
[INFO] (naman) This package is up to date.
[INFO] (namanager) This package is up to date.
[INFO] (namara) This package is up to date.
[INFO] (namaste) This package is up to date.
[INFO] (nambaone) This package is up to date.
[INFO] (nambaone-bot) This package is up to date.
[INFO] (name-cgf) This package is up to date.
[INFO] (name-cleaver) This package is up to date.
[INFO] (name-me) This package is up to date.
[ERROR] (name-meaning) This package does not have downloadable releases.
[INFO] (name-nester) This package is up to date.
[INFO] (name-of) This package is up to date.
[INFO] (name-of-thrones) This package is up to date.
[INFO] (name-suggestor) This package is up to date.
[INFO] (name-tools) This package is up to date.
[INFO] (name2time) This package is up to date.
[INFO] (namealizer) This package is up to date.
[ERROR] (namebot) This package does not have downloadable releases.
[ERROR] (namecheap) This package does not have downloadable releases.
[INFO] (namecheapapi) This package is up to date.
[INFO] (namecom) This package is up to date.
[INFO] (named-bitfield) This package is up to date.
[INFO] (named-constants) This package is up to date.
[INFO] (named-dates) This package is up to date.
[INFO] (named-decorator) This package is up to date.
[INFO] (named-redirect) This package is up to date.
[INFO] (namedatomiclock) This package is up to date.
[INFO] (namedentities) This package is up to date.
[INFO] (namedlist) This package is up to date.
[INFO] (namedmaps) This package is up to date.
[INFO] (namedmatrix) This package is up to date.
[INFO] (namedout) This package is up to date.
[INFO] (namedparser) This package is up to date.
[INFO] (namedropper) This package is up to date.
[INFO] (namedspace) This package is up to date.
[INFO] (namedstruct) This package is up to date.
[INFO] (namedtuple2) This package is up to date.
[INFO] (namedtupled) This package is up to date.
[INFO] (nameforbash) This package is up to date.
[INFO] (namegen) This package is up to date.
[INFO] (namegender) This package is up to date.
[INFO] (namegenerator) This package is up to date.
[INFO] (nameko) This package is up to date.
[INFO] (nameko-amqp-retry) This package is up to date.
[INFO] (nameko-bayeux-client) This package is up to date.
[INFO] (nameko-cache) This package is up to date.
[INFO] (nameko-cachetools) This package is up to date.
[INFO] (nameko-cloudant) This package is up to date.
[INFO] (nameko-dev) This package is up to date.
[INFO] (nameko-eventlog-dispatcher) This package is up to date.
[INFO] (nameko-extras) This package is up to date.
[INFO] (nameko-log-context) This package is up to date.
[INFO] (nameko-logstash) This package is up to date.
[INFO] (nameko-neo4j) This package is up to date.
[INFO] (nameko-nova-compat) This package is up to date.
[INFO] (nameko-objectstorage) This package is up to date.
[INFO] (nameko-opentsdb-py) This package is up to date.
[INFO] (nameko-pony) This package is up to date.
[INFO] (nameko-proxy) This package is up to date.
[ERROR] (nameko-query) This package does not have downloadable releases.
[INFO] (nameko-redis) This package is up to date.
[INFO] (nameko-redis-py) This package is up to date.
[INFO] (nameko-redisy) This package is up to date.
[ERROR] (nameko-rethinkdb) Could not get a response from API for this package. See below for details.
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/pypicontents/api/pypi.py", line 264, in get_pkgdata
    timeout=10).read()
  File "/usr/lib/python3.5/urllib/request.py", line 163, in urlopen
    return opener.open(url, data, timeout)
  File "/usr/lib/python3.5/urllib/request.py", line 472, in open
    response = meth(req, response)
  File "/usr/lib/python3.5/urllib/request.py", line 582, in http_response
    'http', request, response, code, msg, hdrs)
  File "/usr/lib/python3.5/urllib/request.py", line 510, in error
    return self._call_chain(*args)
  File "/usr/lib/python3.5/urllib/request.py", line 444, in _call_chain
    result = func(*args)
  File "/usr/lib/python3.5/urllib/request.py", line 590, in http_error_default
    raise HTTPError(req.full_url, code, msg, hdrs, fp)
urllib.error.HTTPError: HTTP Error 404: Not Found

[INFO] (nameko-salesforce) This package is up to date.
[INFO] (nameko-sendgrid) This package is up to date.
[INFO] (nameko-sentry) This package is up to date.
[INFO] (nameko-slack) This package is up to date.
[INFO] (nameko-socket-server) This package is up to date.
[INFO] (nameko-sqlalchemy) This package is up to date.
[INFO] (nameko-statsd) This package is up to date.
[INFO] (nameko-tracer) This package is up to date.
[INFO] (nameko-twilio) This package is up to date.
[INFO] (nameko-wamp) This package is up to date.
[INFO] (nameko-zipkin) This package is up to date.
[INFO] (nameless) This package is up to date.
[INFO] (nameless-minimal) This package is up to date.
[INFO] (namelist-python) This package is up to date.
[ERROR] (namely) This package does not have downloadable releases.
[INFO] (namemapping) This package is up to date.
[INFO] (namemod) This package is up to date.
[INFO] (namemysprint) This package is up to date.
[INFO] (nameparser) This package is up to date.
[INFO] (nameparts) This package is up to date.
[INFO] (namerator) This package is up to date.
[INFO] (names) This package is up to date.
[INFO] (names-translator) This package is up to date.
[INFO] (namesake) This package is up to date.
[INFO] (namesex) This package is up to date.
[INFO] (namesex-light) This package is up to date.
[INFO] (namesgenerator) This package is up to date.
[INFO] (nameshark-vcard) This package is up to date.
[INFO] (namesilo) This package is up to date.
[INFO] (namespace) This package is up to date.
[INFO] (namespaces) This package is up to date.
[INFO] (namespacetrie) This package is up to date.
[INFO] (namesparser) This package is up to date.
[INFO] (namestand) This package is up to date.
[INFO] (namestyle) This package is up to date.
[INFO] (namesync) This package is up to date.
[INFO] (namethatcolor) This package is up to date.
[INFO] (nametrans) This package is up to date.
[INFO] (naming) This package is up to date.
[INFO] (namlat) This package is up to date.
[INFO] (nampa) This package is up to date.
[INFO] (nams) This package is up to date.
[INFO] (namtso) This package is up to date.
[INFO] (namu-wiki-extractor) This package is up to date.
[INFO] (nana) This package is up to date.
[INFO] (nanester) This package is up to date.
[ERROR] (nanfengyouyi-nester) This package does not have downloadable releases.
[INFO] (nani) This package is up to date.
[INFO] (nani-fighter) This package is up to date.
[INFO] (nannotate) This package is up to date.
[INFO] (nannou) This package is up to date.
[INFO] (nanny) This package is up to date.
[INFO] (nano) This package is up to date.
[INFO] (nano-assault) This package is up to date.
[INFO] (nano-python) This package is up to date.
[ERROR] (nano-restore) This package does not have downloadable releases.
[INFO] (nanoca) This package is up to date.
[INFO] (nanocap) This package is up to date.
[INFO] (nanocom) This package is up to date.
[INFO] (nanocomp) This package is up to date.
[INFO] (nanodb) This package is up to date.
[INFO] (nanodb-driver) This package is up to date.
[INFO] (nanodlna) This package is up to date.
[INFO] (nanofilt) This package is up to date.
[INFO] (nanoflow) This package is up to date.
[INFO] (nanogen) This package is up to date.
[INFO] (nanoget) This package is up to date.
[INFO] (nanogui) This package is up to date.
[INFO] (nanohttp) This package is up to date.
[INFO] (nanoid) This package is up to date.
[INFO] (nanoleaf) This package is up to date.
[INFO] (nanolog) This package is up to date.
[INFO] (nanolp) This package is up to date.
[INFO] (nanolyse) This package is up to date.
[INFO] (nanomath) This package is up to date.
[INFO] (nanomongo) This package is up to date.
[INFO] (nanomsg) This package is up to date.
[INFO] (nanonispy) This package is up to date.
[INFO] (nanopack) This package is up to date.
[INFO] (nanopb-helpers) This package is up to date.
[INFO] (nanoplayboard) This package is up to date.
[INFO] (nanoplot) This package is up to date.
[INFO] (nanoplotter) This package is up to date.
[INFO] (nanopq) Data has been updated for this package.
[INFO] (nanoprobe) This package is up to date.
[INFO] (nanoqc) This package is up to date.
[INFO] (nanoraw) This package is up to date.
[INFO] (nanoretrotect) This package is up to date.
[INFO] (nanorm) This package is up to date.
[INFO] (nanoscope) This package is up to date.
[INFO] (nanoservice) This package is up to date.
[INFO] (nanosim-h) This package is up to date.
[INFO] (nanosimpy) This package is up to date.
[INFO] (nanosite) This package is up to date.
[INFO] (nanosphere) This package is up to date.
[INFO] (nanosplit) This package is up to date.
[INFO] (nanosql) This package is up to date.
[INFO] (nanostat) This package is up to date.
[INFO] (nanostream) This package is up to date.
[INFO] (nanosv) This package is up to date.
[INFO] (nanote) This package is up to date.
[ERROR] (nanotensor) Could not get a response from API for this package. See below for details.
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/pypicontents/api/pypi.py", line 264, in get_pkgdata
    timeout=10).read()
  File "/usr/lib/python3.5/urllib/request.py", line 163, in urlopen
    return opener.open(url, data, timeout)
  File "/usr/lib/python3.5/urllib/request.py", line 472, in open
    response = meth(req, response)
  File "/usr/lib/python3.5/urllib/request.py", line 582, in http_response
    'http', request, response, code, msg, hdrs)
  File "/usr/lib/python3.5/urllib/request.py", line 510, in error
    return self._call_chain(*args)
  File "/usr/lib/python3.5/urllib/request.py", line 444, in _call_chain
    result = func(*args)
  File "/usr/lib/python3.5/urllib/request.py", line 590, in http_error_default
    raise HTTPError(req.full_url, code, msg, hdrs, fp)
urllib.error.HTTPError: HTTP Error 404: Not Found

[ERROR] (nanotest) Could not get a response from API for this package. See below for details.
Traceback (most recent call last):
  File "/usr/lib/python3.5/urllib/request.py", line 1254, in do_open
    h.request(req.get_method(), req.selector, req.data, headers)
  File "/usr/lib/python3.5/http/client.py", line 1107, in request
    self._send_request(method, url, body, headers)
  File "/usr/lib/python3.5/http/client.py", line 1152, in _send_request
    self.endheaders(body)
  File "/usr/lib/python3.5/http/client.py", line 1103, in endheaders
    self._send_output(message_body)
  File "/usr/lib/python3.5/http/client.py", line 934, in _send_output
    self.send(msg)
  File "/usr/lib/python3.5/http/client.py", line 877, in send
    self.connect()
  File "/usr/lib/python3.5/http/client.py", line 1253, in connect
    super().connect()
  File "/usr/lib/python3.5/http/client.py", line 849, in connect
    (self.host,self.port), self.timeout, self.source_address)
  File "/usr/lib/python3.5/socket.py", line 712, in create_connection
    raise err
  File "/usr/lib/python3.5/socket.py", line 703, in create_connection
    sock.connect(sa)
OSError: [Errno 99] Cannot assign requested address

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/pypicontents/api/pypi.py", line 264, in get_pkgdata
    timeout=10).read()
  File "/usr/lib/python3.5/urllib/request.py", line 163, in urlopen
    return opener.open(url, data, timeout)
  File "/usr/lib/python3.5/urllib/request.py", line 466, in open
    response = self._open(req, data)
  File "/usr/lib/python3.5/urllib/request.py", line 484, in _open
    '_open', req)
  File "/usr/lib/python3.5/urllib/request.py", line 444, in _call_chain
    result = func(*args)
  File "/usr/lib/python3.5/urllib/request.py", line 1297, in https_open
    context=self._context, check_hostname=self._check_hostname)
  File "/usr/lib/python3.5/urllib/request.py", line 1256, in do_open
    raise URLError(err)
urllib.error.URLError: <urlopen error [Errno 99] Cannot assign requested address>

[INFO] (nanotime) This package is up to date.
[ERROR] (nanotube) This package does not have downloadable releases.
[INFO] (nanoweb) This package is up to date.
[INFO] (nanowire-plugin) This package is up to date.
[INFO] (nanpy) This package is up to date.
[INFO] (nansat) This package is up to date.
[INFO] (nanshe) This package is up to date.
[INFO] (nanstats) This package is up to date.
[ERROR] (nantic-activity) Could not extract data from this package. See below for details.
This package download URL does not point to a valid file: "https://bitbucket.org/nantic/trytond-activity"
[INFO] (nantic-party-relationship) This package is up to date.
[INFO] (nanyetian-nester) This package is up to date.
[INFO] (nao) This package is up to date.
[INFO] (naobot) This package is up to date.
[INFO] (nap) This package is up to date.
[INFO] (nap-token-auth) This package is up to date.
[INFO] (napa) This package is up to date.
[INFO] (napalm) This package is up to date.
[INFO] (napalm-ansible) This package is up to date.
[INFO] (napalm-aos) This package is up to date.
[INFO] (napalm-asa) This package is up to date.
[INFO] (napalm-base) This package is up to date.
[INFO] (napalm-brocade) This package is up to date.
[INFO] (napalm-ce) This package is up to date.
[INFO] (napalm-eos) This package is up to date.
[INFO] (napalm-exaros) This package is up to date.
[INFO] (napalm-exos) This package is up to date.
[INFO] (napalm-fortios) This package is up to date.
[INFO] (napalm-ibm) This package is up to date.
[INFO] (napalm-ios) This package is up to date.
[INFO] (napalm-iosxr) This package is up to date.
[INFO] (napalm-junos) This package is up to date.
[INFO] (napalm-logs) This package is up to date.
[INFO] (napalm-mos) This package is up to date.
[INFO] (napalm-nxos) This package is up to date.
[INFO] (napalm-panos) This package is up to date.
[INFO] (napalm-pluribus) This package is up to date.
[INFO] (napalm-ros) This package is up to date.
[INFO] (napalm-ruckus-fastiron) This package is up to date.
[INFO] (napalm-salt) This package is up to date.
[INFO] (napalm-vyos) This package is up to date.
[INFO] (napalm-yang) This package is up to date.
[INFO] (napari) This package is up to date.
[INFO] (napi) This package is up to date.
[ERROR] (napoleon) This package does not have downloadable releases.
[INFO] (napoleon2html) This package is up to date.
[INFO] (naposapi) This package is up to date.
[INFO] (napper) This package is up to date.
[ERROR] (nappingcat) This package does not have downloadable releases.
[INFO] (nappy) This package is up to date.
[INFO] (nara-wpe) This package is up to date.
[INFO] (narc-testrun-finished) This package is up to date.
[INFO] (narcissus-app) This package is up to date.
[INFO] (narcissus-common) This package is up to date.
[INFO] (narcissus-hub) This package is up to date.
[INFO] (narcolepsy) This package is up to date.
[INFO] (narcwar) This package is up to date.
[INFO] (nardis) This package is up to date.
[INFO] (nark) This package is up to date.
[INFO] (narmer) This package is up to date.
[INFO] (narrative) This package is up to date.
[INFO] (narrow) This package is up to date.
[INFO] (narrowband) This package is up to date.
[INFO] (naruhodo) This package is up to date.
[INFO] (naruto) This package is up to date.
[INFO] (narval) This package is up to date.
[INFO] (narwal) This package is up to date.
[INFO] (narwhal) This package is up to date.
[INFO] (nas-code-checker) This package is up to date.
[INFO] (nasa-api-wrapper) This package is up to date.
[INFO] (nasa-tle-loader) This package is up to date.
[INFO] (nasalgeom) This package is up to date.
[INFO] (nasdaq-stock) This package is up to date.
[INFO] (nasdaq-stock-quote) This package is up to date.
[INFO] (nash) This package is up to date.
[INFO] (nasheri) This package is up to date.
[INFO] (nashi) This package is up to date.
[INFO] (nashpy) This package is up to date.
[INFO] (nashvegas) This package is up to date.
[INFO] (nasl-parser) This package is up to date.
[INFO] (nasm) This package is up to date.
[INFO] (nasp) This package is up to date.
[INFO] (nass) This package is up to date.
[INFO] (nassl) This package is up to date.
[INFO] (nasst) This package is up to date.
[INFO] (naster) This package is up to date.
[ERROR] (naster-2016825) Could not get a response from API for this package. See below for details.
Traceback (most recent call last):
  File "/usr/lib/python3.5/urllib/request.py", line 1254, in do_open
    h.request(req.get_method(), req.selector, req.data, headers)
  File "/usr/lib/python3.5/http/client.py", line 1107, in request
    self._send_request(method, url, body, headers)
  File "/usr/lib/python3.5/http/client.py", line 1152, in _send_request
    self.endheaders(body)
  File "/usr/lib/python3.5/http/client.py", line 1103, in endheaders
    self._send_output(message_body)
  File "/usr/lib/python3.5/http/client.py", line 934, in _send_output
    self.send(msg)
  File "/usr/lib/python3.5/http/client.py", line 877, in send
    self.connect()
  File "/usr/lib/python3.5/http/client.py", line 1253, in connect
    super().connect()
  File "/usr/lib/python3.5/http/client.py", line 849, in connect
    (self.host,self.port), self.timeout, self.source_address)
  File "/usr/lib/python3.5/socket.py", line 712, in create_connection
    raise err
  File "/usr/lib/python3.5/socket.py", line 703, in create_connection
    sock.connect(sa)
OSError: [Errno 99] Cannot assign requested address

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/pypicontents/api/pypi.py", line 264, in get_pkgdata
    timeout=10).read()
  File "/usr/lib/python3.5/urllib/request.py", line 163, in urlopen
    return opener.open(url, data, timeout)
  File "/usr/lib/python3.5/urllib/request.py", line 472, in open
    response = meth(req, response)
  File "/usr/lib/python3.5/urllib/request.py", line 582, in http_response
    'http', request, response, code, msg, hdrs)
  File "/usr/lib/python3.5/urllib/request.py", line 504, in error
    result = self._call_chain(*args)
  File "/usr/lib/python3.5/urllib/request.py", line 444, in _call_chain
    result = func(*args)
  File "/usr/lib/python3.5/urllib/request.py", line 696, in http_error_302
    return self.parent.open(new, timeout=req.timeout)
  File "/usr/lib/python3.5/urllib/request.py", line 466, in open
    response = self._open(req, data)
  File "/usr/lib/python3.5/urllib/request.py", line 484, in _open
    '_open', req)
  File "/usr/lib/python3.5/urllib/request.py", line 444, in _call_chain
    result = func(*args)
  File "/usr/lib/python3.5/urllib/request.py", line 1297, in https_open
    context=self._context, check_hostname=self._check_hostname)
  File "/usr/lib/python3.5/urllib/request.py", line 1256, in do_open
    raise URLError(err)
urllib.error.URLError: <urlopen error [Errno 99] Cannot assign requested address>

[INFO] (naster-dmtang) This package is up to date.
[INFO] (naster-sytang) This package is up to date.
[INFO] (nastools) This package is up to date.
[INFO] (nastran-pch-reader) This package is up to date.
[INFO] (nastranpy) This package is up to date.
[INFO] (nat) This package is up to date.
[INFO] (nat-cloud) This package is up to date.
[INFO] (nat-pmp) This package is up to date.
[INFO] (natasha) This package is up to date.
[INFO] (natcap-invest) This package is up to date.
[INFO] (natcap-opal) This package is up to date.
[INFO] (natcap-rios) This package is up to date.
[INFO] (natcap-versioner) This package is up to date.
[INFO] (natcloud) This package is up to date.
[INFO] (natera-uploader) This package is up to date.
[ERROR] (natex-ads-api) Could not get a response from API for this package. See below for details.
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/pypicontents/api/pypi.py", line 264, in get_pkgdata
    timeout=10).read()
  File "/usr/lib/python3.5/urllib/request.py", line 163, in urlopen
    return opener.open(url, data, timeout)
  File "/usr/lib/python3.5/urllib/request.py", line 472, in open
    response = meth(req, response)
  File "/usr/lib/python3.5/urllib/request.py", line 582, in http_response
    'http', request, response, code, msg, hdrs)
  File "/usr/lib/python3.5/urllib/request.py", line 504, in error
    result = self._call_chain(*args)
  File "/usr/lib/python3.5/urllib/request.py", line 444, in _call_chain
    result = func(*args)
  File "/usr/lib/python3.5/urllib/request.py", line 696, in http_error_302
    return self.parent.open(new, timeout=req.timeout)
  File "/usr/lib/python3.5/urllib/request.py", line 472, in open
    response = meth(req, response)
  File "/usr/lib/python3.5/urllib/request.py", line 582, in http_response
    'http', request, response, code, msg, hdrs)
  File "/usr/lib/python3.5/urllib/request.py", line 510, in error
    return self._call_chain(*args)
  File "/usr/lib/python3.5/urllib/request.py", line 444, in _call_chain
    result = func(*args)
  File "/usr/lib/python3.5/urllib/request.py", line 590, in http_error_default
    raise HTTPError(req.full_url, code, msg, hdrs, fp)
urllib.error.HTTPError: HTTP Error 404: Not Found

[INFO] (natgeo-photo) This package is up to date.
[ERROR] (nathan-nester) This package does not have downloadable releases.
[INFO] (nationstates) This package is up to date.
[INFO] (nativdebugging) This package is up to date.
[ERROR] (native-instrument-assingment) This package does not have downloadable releases.
[INFO] (nativeconfig) This package is up to date.
[INFO] (nativeimaging) This package is up to date.
[INFO] (nativetypes) This package is up to date.
[INFO] (nativo) This package is up to date.
[INFO] (natlight) This package is up to date.
[INFO] (natnetclient) This package is up to date.
[ERROR] (natrix) This package does not have downloadable releases.
[ERROR] (nats) This package does not have downloadable releases.
[INFO] (nats-client) This package is up to date.
[INFO] (nats-scan-wrapper) This package is up to date.
[INFO] (natsort) This package is up to date.
[INFO] (natspec-utils) This package is up to date.
[INFO] (natto) This package is up to date.
[INFO] (natto-py) This package is up to date.
[INFO] (nattraverso) This package is up to date.
[INFO] (natty) This package is up to date.
[INFO] (natu) This package is up to date.
[INFO] (natume) This package is up to date.
[INFO] (natura) This package is up to date.
[INFO] (natural) This package is up to date.
[INFO] (natural-keys) This package is up to date.
[INFO] (natural-money) This package is up to date.
[INFO] (natural-time) This package is up to date.
[INFO] (natural3) This package is up to date.
[INFO] (naturalneighbor) This package is up to date.
[INFO] (naturalsort) This package is up to date.
[INFO] (naturecrawl) This package is up to date.
[INFO] (nau-net) This package is up to date.
[INFO] (nau-orchard) This package is up to date.
[INFO] (naughties) This package is up to date.
[INFO] (naughty) This package is up to date.
[INFO] (nauka) This package is up to date.
[INFO] (nauth) This package is up to date.
[INFO] (nautilus) This package is up to date.
[ERROR] (nautilus-blacklist) This package does not have downloadable releases.
[INFO] (nautilus-registry) This package is up to date.
[INFO] (nautilus-reigstry) This package is up to date.
[INFO] (nautilus-terminal) This package is up to date.
[INFO] (nautiluspy) This package is up to date.
[INFO] (nav) This package is up to date.
[INFO] (nav-requests) This package is up to date.
[INFO] (navadd) This package is up to date.
[INFO] (naval) This package is up to date.
[INFO] (navdoon) This package is up to date.
[INFO] (navegador5) This package is up to date.
[INFO] (naver-book-query) This package is up to date.
[INFO] (naverblogbackup) This package is up to date.
[ERROR] (naverdic) This package does not have downloadable releases.
[INFO] (naverlogin) This package is up to date.
[INFO] (navernews) This package is up to date.
[ERROR] (naverwebtoonfeeds) This package does not have downloadable releases.
[INFO] (navi) This package is up to date.
[INFO] (naviance-client) This package is up to date.
[INFO] (navigator) This package is up to date.
[INFO] (navio-aws) This package is up to date.
[INFO] (navio-builder) This package is up to date.
[INFO] (navio2) This package is up to date.
[ERROR] (navitia) This package does not have downloadable releases.
[INFO] (navitia-client) This package is up to date.
[INFO] (navmazing) This package is up to date.
[INFO] (navtrix) This package is up to date.
[INFO] (navy-first) This package is up to date.
[INFO] (nawa) This package is up to date.
[INFO] (naya) This package is up to date.
[INFO] (nayesdog) This package is up to date.
[INFO] (naz) This package is up to date.
[ERROR] (naz-examples) This package does not have downloadable releases.
[INFO] (nazca) This package is up to date.
[INFO] (nazoru-input) This package is up to date.
[INFO] (nb) This package is up to date.
[INFO] (nb-clean) This package is up to date.
[INFO] (nb-lua-kernel) This package is up to date.
[INFO] (nb-mermaid) This package is up to date.
[INFO] (nb-pdf-template) This package is up to date.
[INFO] (nb-toc) This package is up to date.
[INFO] (nb2kg) This package is up to date.
[INFO] (nb2mail) This package is up to date.
[INFO] (nb2plots) This package is up to date.
[INFO] (nb2py) This package is up to date.
[ERROR] (nba) This package does not have downloadable releases.
[INFO] (nba-data) This package is up to date.
[INFO] (nba-images-client) This package is up to date.
[INFO] (nba-py) This package is up to date.
[INFO] (nba-stats) This package is up to date.
[INFO] (nback) This package is up to date.
[INFO] (nbacli) This package is up to date.
[INFO] (nbadata) This package is up to date.
[INFO] (nbahub) This package is up to date.
[INFO] (nbanumbers) This package is up to date.
[INFO] (nbapipy) This package is up to date.
[ERROR] (nbapp) This package does not have downloadable releases.
[INFO] (nbashots) This package is up to date.
[INFO] (nbastats) This package is up to date.
[INFO] (nbautoeval) This package is up to date.
[INFO] (nbawebstats) This package is up to date.
[INFO] (nbbrowserpdf) This package is up to date.
[INFO] (nbclean) This package is up to date.
[INFO] (nbcollate) This package is up to date.
[INFO] (nbcomet) This package is up to date.
[INFO] (nbconflux) This package is up to date.
[INFO] (nbconvert) This package is up to date.
[INFO] (nbconvert-grader) This package is up to date.
[INFO] (nbconvert-pyencoded) This package is up to date.
[INFO] (nbconvert-reportlab) This package is up to date.
[INFO] (nbconvert-watch) This package is up to date.
[INFO] (nbcrawler) This package is up to date.
[INFO] (nbd) This package is up to date.
[INFO] (nbdebug) This package is up to date.
[WARNING] 
[WARNING] Processing has taken more than 2100 seconds. Interrupting.
[WARNING] Processing will continue in next iteration.
[WARNING] 
[INFO] 
[INFO] 
[INFO] Total packages: 4385
[INFO]     Packages processed: 509
[INFO]         Packages updated: 1
[INFO]         Packages up-to-date: 467
[INFO]         Packages without response: 9
[INFO]         Packages without urls: 0
[INFO]         Packages without downloads: 29
[INFO]         Packages with data errors: 3
[INFO]     Packages not processed: 3876
[INFO] 
[INFO] 
[INFO] Ending execution.
